Repository andela/travel_tool_front, pull requests merged in 2018-09, with the labels that each got.

#78 #160238493 Fix details modal display on mobile
  src/components/RequestsModal/CommentBox/_CommentBox.scss
  src/components/RequestsModal/RequestsModal.scss
  src/components/modal/_modal.scss
  src/components/nav-bar/NavBar.scss
  src/views/RequestsPage/RequestsPage.scss
Labels: ready

#75 #160046190 Fix Request Page Reloading
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItem/LeftSideNavItem.jsx
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItem/__tests__/LeftsideNavItem.test.jsx
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItem/__tests__/__snapshots__/LeftsideNavItem.test.jsx.snap
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItems.jsx
  src/components/LeftSideBar/LeftSideNavItems/__tests__/LeftSideNavItems.test.jsx
  src/components/LeftSideBar/LeftSideNavItems/__tests__/__snapshots__/LeftSideNavItems.test.jsx.snap
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/SideDrawer/SideDrawer.jsx
  src/components/SideDrawer/SideDrawer.scss
  src/components/nav-bar/NavBar.jsx
  src/components/nav-bar/NavBar.scss
  src/components/nav-bar/__tests__/NavBar.test.js
  src/components/nav-bar/__tests__/__snapshots__/NavBar.test.js.snap
  src/views/ApprovalsPage/__tests__/ApprovalsPage.test.js
  src/views/ApprovalsPage/index.jsx
  src/views/Base/index.jsx
  src/views/RequestsPage/RequestsPage.jsx
  src/views/RequestsPage/RequestsPage.scss
  src/views/RequestsPage/__tests__/__snapshots__/RequestsPage.test.js.snap
Labels: ready

#76 #160168277 Get profile information from travel request page
  config/setupTests.js
  src/components/ApprovalsPanelHeader/__tests__/ApprovalsPanelHeader.test.js
  src/components/CheckBox/Checkbox.scss
  src/components/CheckBox/__tests__/Checkbox.test.js
  src/components/CheckBox/__tests__/__snapshots__/Checkbox.test.js.snap
  src/components/CheckBox/index.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewRequestForm/__tests__/__snapshots__/NewRequestForm.test.jsx.snap
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/nav-bar/NavBar.jsx
  src/components/nav-bar/__tests__/__snapshots__/NavBar.test.js.snap
  src/images/Tick/tick.svg
  src/routes/index.js
  src/services/RequestAPI.js
Labels: ready

#80 #160233501 Assigning manager role to user
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewRequestForm/__tests__/__snapshots__/NewRequestForm.test.jsx.snap
  src/components/Pagination/Pagination.jsx
  src/components/Pagination/__tests__/Pagination.test.js
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/SelectDropDown/SelectDropDown.jsx
  src/components/button-group/__tests__/__snapshots__/ButtonGroup.tests.js.snap
  src/components/buttons/Buttons.jsx
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/__tests__/roleActions.js
  src/redux/actionCreator/roleActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/roleSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/roleSaga.js
  src/redux/reducers/__tests__/role.test.js
  src/redux/reducers/index.js
  src/redux/reducers/role.js
  src/services/RequestAPI.js
  src/services/RoleAPI.js
  src/services/__tests__/RoleAPI.test.js
  src/views/RequestsPage/RequestsPage.jsx
  src/views/RequestsPage/__tests__/RequestsPage.test.js
  src/views/RequestsPage/__tests__/__snapshots__/RequestsPage.test.js.snap
Labels: ready

#83 #160250660 Set height for landing page
  src/components/TextLink/TextLink.jsx
  src/views/Login/Login.scss
Labels: ready

#82 #160195740 Display Request Details On Modal
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/RequestsModal.scss
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Table/index.jsx
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/requestActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/requestsSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/requestsSaga.js
  src/redux/middleware/roleSaga.js
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/requests.js
  src/services/RequestAPI.js
Labels: ready

#84 #160220034 Fix Travel Request Form
  src/components/Forms/FormsAPI/Input/InputFields/Date.jsx
  src/components/Forms/FormsAPI/Input/__tests__/__snapshots__/index.test.jsx.snap
  src/components/Forms/FormsAPI/Input/_input.scss
  src/components/Forms/FormsAPI/Input/index.jsx
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/SubmitArea.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Forms/NewRequestForm/__tests__/__snapshots__/NewRequestForm.test.jsx.snap
  src/components/Forms/NewUserRoleForm/__test__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/nav-bar/NavBar.scss
  src/views/Base/index.jsx
  src/views/RequestsPage/RequestsPage.scss
Labels: ready

#90 #160047854 User Roles Settings
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/RolePanelHeader/RolePanelHeader.scss
  src/components/RoleTable/RoleTable.scss
  src/components/RoleTable/index.jsx
Labels: completed

#79 #160195763 Allow users create comments
  package.json
  src/components/RequestsModal/CommentBox/CommentBox.jsx
  src/components/RequestsModal/CommentBox/__test__/CommentBox.test.js
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/RequestsModal.scss
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/__tests__/commentsActions.test.js
  src/redux/actionCreator/commentsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/commentsSaga.test.js
  src/redux/middleware/__tests__/requestsSaga.test.js
  src/redux/middleware/commentsSaga.js
  src/redux/middleware/index.js
  src/redux/middleware/requestsSaga.js
  src/redux/reducers/__tests__/comments.test.js
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/comments.js
  src/redux/reducers/index.js
  src/services/CommentsAPI.js
  src/services/__tests__/CommentsAPI.test.js
  src/views/ApprovalsPage/__tests__/ApprovalsPage.test.js
  src/views/RequestsPage/__tests__/RequestsPage.test.js
  yarn.lock
Labels: ready

#67 #160047860 Implement Table Filters on `My Approvals` Page
  src/components/ApprovalsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
  src/components/ApprovalsPanelHeader/index.jsx
  src/components/Forms/FormsAPI/Input/InputFields/Date.jsx
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/button-group/ButtonGroup.jsx
  src/components/button-group/__tests__/ButtonGroup.tests.js
  src/mockData/requestsMockData.js
  src/redux/__mocks__/approvalsResponses.js
  src/redux/__mocks__/mockAxios.js
  src/redux/actionCreator/approvalActions.js
  src/redux/actionCreator/index.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/approvalsSaga.test.js
  src/redux/middleware/approvalsSaga.js
  src/redux/middleware/index.js
  src/redux/middleware/requestsSaga.js
  src/redux/reducers/__tests__/approvals.test.js
  src/redux/reducers/approvals.js
  src/redux/reducers/index.js
  src/routes/index.js
  src/services/RequestAPI.js
  src/services/approvalsAPI.js
  src/services/index.js
  src/views/ApprovalsPage/__tests__/ApprovalsPage.test.js
  src/views/ApprovalsPage/index.jsx
  src/views/Base/index.jsx
  src/views/RequestsPage/RequestsPage.jsx
Labels: ready

#77 #160196032 Approve and Reject request(By Requester's Manager)
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/__tests__/__snapshots__/NewRequestForm.test.jsx.snap
  src/components/RequestsModal/CommentBox/AddComment.jsx
  src/components/RequestsModal/CommentBox/__test__/AddComment.test.js
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/AddComment.test.js.snap
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/helper/generateDynamicDate.js
  src/helper/isCurrentPageMyApproval.js
  src/redux/actionCreator/__tests__/approvalAction.test.js
  src/redux/actionCreator/approvalActions.js
  src/redux/actionCreator/index.js
  src/redux/actionCreator/requestActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/approvalsSaga.test.js
  src/redux/middleware/approvalsSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/approvals.test.js
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/approvals.js
  src/redux/reducers/requests.js
  src/routes/index.js
  src/services/__tests__/ApprovalAPI.test.js
  src/services/approvalsAPI.js
  src/views/ApprovalsPage/index.jsx
Labels: ready

#95 #160343793 Fix missing destination column for mobile view
  src/components/Forms/FormsAPI/Input/_input.scss
  src/components/Table/index.jsx
Labels: ready

#88 #160157497 Setup bugsnag for error reporting
  .env.example
  package.json
  src/views/App/App.jsx
  yarn.lock
Labels: devops-review

#96 #160196032 Approve/Reject Request (By Requester's Manager)
  src/components/RequestsModal/CommentBox/__tests__/AddComment.test.js
  src/components/RequestsModal/CommentBox/__tests__/CommentBox.test.js
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/AddComment.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/CommentBox.test.js.snap
  src/components/RequestsModal/RequestInfo/RequestInfo.jsx
  src/components/RequestsModal/RequestInfo/__tests__/RequestInfo.test.js
  src/components/RequestsModal/RequestInfo/__tests__/__snapshots__/RequestInfo.test.js.snap
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/UserComments/UserComments.jsx
  src/components/RequestsModal/UserComments/__tests__/UserComments.test.js
  src/components/RequestsModal/UserComments/__tests__/__snapshots__/UserComments.test.js.snap
  src/components/RequestsModal/UserInfo/UserInfo.jsx
  src/components/RequestsModal/UserInfo/__tests__/UserInfo.test.js
  src/components/RequestsModal/UserInfo/__tests__/__snapshots__/UserInfo.test.js.snap
  src/components/RequestsModal/__mocks__/requestData.js
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Table/index.jsx
  src/helper/isCurrentPageMyApproval.js
  src/redux/actionCreator/modalActions.js
  src/redux/reducers/__tests__/approvals.test.js
  src/redux/reducers/__tests__/modals.test.js
  src/redux/reducers/approvals.js
  src/redux/reducers/modal.js
  src/views/Approvals/__tests__/Approvals.test.js
  src/views/Approvals/index.jsx
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
Labels: ready

#110 #160429451 Correct the Application Name
  .circleci/build_deploy.sh
  .circleci/config.yml
  .circleci/load_env_variables.sh
Labels: devops-review

#109 #160370617 One way trip with new request modal
  .env.example
  .eslintrc.json
  config/setupTests.js
  package.json
  src/components/CheckBox/__tests__/__snapshots__/Checkbox.test.js.snap
  src/components/CheckBox/index.jsx
  src/components/Forms/FormsAPI/Input/InputFields/Date.jsx
  src/components/Forms/FormsAPI/Input/InputFields/DropdownSelect.jsx
  src/components/Forms/FormsAPI/Input/InputFields/HtmlInput.jsx
  src/components/Forms/FormsAPI/Input/InputFields/index.js
  src/components/Forms/FormsAPI/Input/_input.scss
  src/components/Forms/FormsAPI/Input/index.jsx
  src/components/Forms/FormsAPI/formEventHandlers/eventHandlerCreators.js
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/inputLabels.js
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewRequestForm/__tests__/__snapshots__/NewRequestForm.test.jsx.snap
  src/components/Forms/NewUserRoleForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewUserRoleForm/NewUserRoleForm.jsx
  src/components/Forms/NewUserRoleForm/__test__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/Forms/index.js
  src/components/Forms/index.scss
  src/components/RadioButton/RaidoButton.scss
  src/components/RadioButton/__test__/RaidoButton.test.js
  src/components/RadioButton/__test__/__snapshots__/RaidoButton.test.js.snap
  src/components/RadioButton/index.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/Table/index.jsx
  src/components/modal/Modal.jsx
  src/components/modal/__tests__/__snapshots__/Modal.test.jsx.snap
  src/helper/toast.js
  src/images/expand_more_24px 2.svg
  src/images/expand_more_24px.svg
  src/images/icons/location.svg
  src/images/location.svg
  src/views/App/App.scss
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
  src/views/Role/index.jsx
  yarn.lock
Labels: ready

#111 #160370625 Edit posted comments
  src/components/RequestsModal/CommentBox/CommentBox.jsx
  src/components/RequestsModal/CommentBox/_CommentBox.scss
  src/components/RequestsModal/CommentBox/__tests__/CommentBox.test.js
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/CommentBox.test.js.snap
  src/components/RequestsModal/RequestsModal.scss
  src/components/RequestsModal/UserComments/UserComments.jsx
  src/components/RequestsModal/UserComments/__tests__/UserComments.test.js
  src/components/RequestsModal/UserComments/__tests__/__snapshots__/UserComments.test.js.snap
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/commentsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/commentsSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/comments.test.js
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/comments.js
  src/redux/reducers/requests.js
  src/services/CommentsAPI.js
Labels: ready

#103 #160128175 Create user profile page
  src/components/CheckBox/__tests__/Checkbox.test.js
  src/components/Forms/FormsMetadata/NewProfileMetadata/buttonToggleOptions.js
  src/components/Forms/FormsMetadata/NewProfileMetadata/dropdownSelect.js
  src/components/Forms/FormsMetadata/NewProfileMetadata/index.js
  src/components/Forms/FormsMetadata/NewProfileMetadata/inputLabels.js
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewUserRoleForm/__test__/NewUserRoleForm.test.js
  src/components/Forms/ProfileForm/FormFieldsets/ProfileDetails.jsx
  src/components/Forms/ProfileForm/ProfileForm.scss
  src/components/Forms/ProfileForm/_tests_/ProfileForm.test.jsx
  src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
  src/components/Forms/ProfileForm/index.jsx
  src/components/Forms/index.js
  src/components/LeftSideBar/LeftSideNavItems/__tests__/LeftSideNavItems.test.jsx
  src/components/LeftSideBar/Metadata/index.js
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/redux/actionCreator/requestActions.js
  src/redux/actionCreator/userActions.js
  src/redux/actionCreator/userProfileActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/UserProfileSaga.js
  src/redux/middleware/__tests__/userProfileSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/requestsSaga.js
  src/routes/index.js
  src/services/ProfileApi.js
  src/services/__tests__/UserAPI.test.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/index.jsx
  src/views/UserProfile/UserProfile.scss
  src/views/UserProfile/__tests__/UserProfile.test.js
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
  src/views/UserProfile/index.jsx
Labels: ready

#114 #160524684 Add video to the link with label 'How to book a trip'
  src/views/Login/index.jsx
Labels: ready

#106 #160371193 Edit Travel Request Notifications
  src/components/RouterModal/index.jsx
  src/components/modal/Modal.jsx
  src/components/modal/__tests__/__snapshots__/Modal.test.jsx.snap
  src/components/modal/overlay/_overlay.scss
  src/components/notification-pane/NotificationContainer.jsx
  src/components/notification-pane/NotificationItem.jsx
  src/components/notification-pane/NotificationPane.jsx
  src/components/notification-pane/__tests__/NotificationItem.test.js
  src/components/notification-pane/__tests__/NotificationPane.test.js
  src/helper/socket/socket.js
  src/hoc/Layout/__tests__/Layout.test.jsx
  src/hoc/Layout/index.jsx
  src/redux/actionCreator/notificationsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/notificationsSaga.test.js
  src/redux/middleware/approvalsSaga.js
  src/redux/middleware/index.js
  src/redux/middleware/notificationSaga.js
  src/redux/middleware/notificationsSaga.js
  src/redux/reducers/index.js
  src/redux/reducers/notifications.js
  src/routes/index.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  yarn.lock
Labels: ready

#115 #160371607 Checkbox status should be cached
  src/components/CheckBox/__tests__/Checkbox.test.js
  src/components/CheckBox/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Forms/NewRequestForm/__tests__/__snapshots__/NewRequestForm.test.jsx.snap
Labels: ready

#123 #160645740 Fix notification pane width and message bug
  src/components/notification-pane/NotificationPane.jsx
  src/components/notification-pane/_notificationPane.scss
  src/redux/reducers/notifications.js
Labels: ready

#121 #160371227 Update notification pane
  src/components/RequestsModal/CommentBox/AddComment.jsx
  src/components/RequestsModal/RequestsModal.jsx
  src/components/notification-pane/NotificationContainer.jsx
  src/components/notification-pane/NotificationItem.jsx
Labels: ready

#127 #160663195 Fix Approve and Reject Button Color
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/AddComment.test.js.snap
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/RouterModal/__tests__/routerModal.test.js
  src/components/RouterModal/index.jsx
Labels: ready

#128 #160673841 Restrict editing comment to the owner only
  src/components/RequestsModal/CommentBox/_CommentBox.scss
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/UserComments/UserComments.jsx
  src/components/RequestsModal/UserComments/__tests__/UserComments.test.js
  src/components/RequestsModal/UserComments/__tests__/__snapshots__/UserComments.test.js.snap
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/redux/__mocks__/mocks.js
  src/redux/reducers/requests.js
Labels: ready

#129 #160663195 Fix the Approve or Reject Button Text
  src/components/RequestsModal/RequestsModal.jsx
Labels: ready

#116 #160386275 Fix travel duration
  src/components/Forms/FormsAPI/Input/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/redux/reducers/__tests__/requests.test.js
  src/views/Approvals/__tests__/Approvals.test.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
Labels: ready

#136 #160370625 Write test for edit comment functionality
  src/components/RequestsModal/CommentBox/__tests__/CommentBox.test.js
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/UserComments/UserComments.jsx
  src/components/RequestsModal/UserComments/__tests__/UserComments.test.js
  src/components/RequestsModal/UserComments/__tests__/__snapshots__/UserComments.test.js.snap
  src/redux/actionCreator/__tests__/commentsActions.test.js
  src/redux/middleware/__tests__/commentsSaga.test.js
  src/redux/reducers/__tests__/comments.test.js
  src/services/__tests__/CommentsAPI.test.js
Labels: ready

#144 #160371227 A requester should be able to view approved request
  src/components/notification-pane/NotificationContainer.jsx
  src/components/notification-pane/NotificationItem.jsx
  src/components/notification-pane/__tests__/NotificationItem.test.js
Labels: ready

#141 Update test new request modal
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewRequestForm/__tests__/__snapshots__/NewRequestForm.test.jsx.snap
Labels: ready

#135 #160685068 Get user friendly trip type message
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/views/Approvals/__tests__/Approvals.test.js
Labels: ready

#117 #160371487 Mark all notifications as read
  package.json
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/nav-bar/NavBar.jsx
  src/components/nav-bar/__mocks__/notificationMockData.js
  src/components/nav-bar/__tests__/NavBar.test.js
  src/components/nav-bar/__tests__/__snapshots__/NavBar.test.js.snap
  src/components/notification-pane/NotificationContainer.jsx
  src/components/notification-pane/NotificationItem.jsx
  src/components/notification-pane/NotificationPane.jsx
  src/components/notification-pane/__mocks__/notificationMockData.js
  src/components/notification-pane/__tests__/NotificationContainer.test.js
  src/components/notification-pane/__tests__/NotificationPane.test.js
  src/components/notification-pane/_notificationContainer.scss
  src/helper/notifications-helper.js
  src/hoc/Layout/__tests__/Layout.test.jsx
  src/hoc/Layout/__tests__/__snapshots__/Layout.test.jsx.snap
  src/hoc/Layout/index.jsx
  src/redux/__mocks__/notificationsMockData.js
  src/redux/actionCreator/__tests__/notificationsActions.test.js
  src/redux/actionCreator/index.js
  src/redux/actionCreator/notificationsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/notificationsSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/notificationsSaga.js
  src/redux/reducers/__tests__/notifications.test.js
  src/redux/reducers/notifications.js
  src/services/NotificationsAPI.js
  src/services/__tests__/NotificationsAPI.test.js
Labels: ready

#143 #160371607 Checkbox status should be cached
  src/components/CheckBox/__tests__/Checkbox.test.js
  src/components/CheckBox/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewRequestForm/__tests__/PersonalDetailsFieldset.test.jsx
Labels: ready

#147 #160729953 Rearrange column positions for destination and origin
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/TripDetails/index.jsx
Labels: ready

#146 #160749054 Fix Request Modal Background
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RouterModal/__tests__/routerModal.test.js
  src/components/RouterModal/index.jsx
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/modal/Modal.jsx
  src/components/modal/__tests__/__snapshots__/Modal.test.jsx.snap
  src/routes/index.js
  src/views/Approvals/__tests__/Approvals.test.js
  src/views/Approvals/index.jsx
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
Labels: ready

#153 #160751452 Re-order arrangement of notifications
  src/components/notification-pane/NotificationContainer.jsx
Labels: ready

#137 #160370764 Search functionality
  package.json
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/button-group/ButtonGroup.jsx
  src/components/modal/Modal.jsx
  src/components/nav-bar/NavBar.jsx
  src/components/nav-bar/__tests__/NavBar.test.js
  src/components/nav-bar/__tests__/__snapshots__/NavBar.test.js.snap
  src/components/search-bar/SearchBar.jsx
  src/components/search-bar/__tests__/SearchBar.test.js
  src/components/search-bar/__tests__/__snapshots__/SearchBar.test.js.snap
  src/helper/Utils.js
  src/views/Approvals/index.jsx
  src/views/Requests/index.jsx
  yarn.lock
Labels: ready

#152 #160751466 Show toaster when notification is sent
  src/helper/socket/__tests__/socket.test.js
  src/helper/socket/socket.js
  src/sounds/notification.mp3
Labels: ready

#145 #160370638 Delete comment functionality
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/UserComments/CommentItem.jsx
  src/components/RequestsModal/UserComments/UserComments.jsx
  src/components/RequestsModal/UserComments/UserComments.scss
  src/components/RequestsModal/UserComments/__tests__/CommentItem.test.js
  src/components/RequestsModal/UserComments/__tests__/UserComments.test.js
  src/components/RequestsModal/UserComments/__tests__/__snapshots__/CommentItem.test.js.snap
  src/components/RequestsModal/UserComments/__tests__/__snapshots__/UserComments.test.js.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/modal/Modal.jsx
  src/components/modal/__tests__/__snapshots__/Modal.test.jsx.snap
  src/components/modal/overlay/Overlay.jsx
  src/components/modal/overlay/_overlay.scss
  src/redux/actionCreator/__tests__/commentsActions.test.js
  src/redux/actionCreator/commentsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/commentsSaga.test.js
  src/redux/middleware/commentsSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/comments.test.js
  src/redux/reducers/comments.js
  src/services/CommentsAPI.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
Labels: ready

#157 #160751476 Restyle toasts to match style guide
  src/customStyles/toast.scss
  src/helper/toast.js
  src/images/toast-cancel-white.svg
  src/images/toast-cancel.svg
  src/views/App/index.jsx
Labels: ready

#154 #160724471 Confirmation dialog for approval
  src/components/RequestsModal/CommentBox/RequestApproval.jsx
  src/components/RequestsModal/CommentBox/__tests__/RequestApproval.test.js
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/ConfirmDialog/ConfirmDialog.jsx
  src/components/RequestsModal/ConfirmDialog/ConfirmDialog.scss
  src/components/RequestsModal/ConfirmDialog/__tests__/ConfirmDialog.test.js
  src/components/RequestsModal/ConfirmDialog/__tests__/__snapshots__/ConfirmDialog.test.js.snap
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/RequestsModal.scss
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/redux/middleware/approvalsSaga.js
Labels: ready
