Repository andela/travel_tool_front, pull requests merged in 2018-08, with the labels that each got.

#39 #159467252 Make the login page mobile responsive
  .gitignore
  src/views/Login/Login.jsx
  src/views/Login/Login.scss
Labels: Completed

#46 #159724830 Create and style the approvals table
  package.json
  src/components/ApprovalsPanelHeader/__tests__/ApprovalsPanelHeader.test.js
  src/components/ApprovalsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
  src/components/ApprovalsPanelHeader/index.jsx
  src/components/PageHeader/_header.scss
  src/components/PageHeader/index.jsx
  src/components/RequestPanelHeader/RequestPanelHeader.jsx
  src/components/Requests/requestsData.js
  src/components/Table/Table.scss
  src/components/Table/__tests__/Table.test.js
  src/components/Table/_approvals.scss
  src/components/Table/index.jsx
  src/components/button-group/ButtonGroup.jsx
  src/components/button-group/buttonGroup.scss
  src/components/header/Header.jsx
  src/images/approvals/fifth.png
  src/images/approvals/fourth.png
  src/images/approvals/harrison.png
  src/images/approvals/second.png
  src/images/approvals/third.png
  src/mockData/requestsMockData.js
  src/routes/index.js
  src/views/App/__tests__/__snapshots__/Request.test.js.snap
  src/views/ApprovalsPage/__tests__/ApprovalsPage.test.js
  src/views/ApprovalsPage/index.jsx
  src/views/Base/index.jsx
  src/views/RequestsPage/RequestsPage.jsx
  src/views/RequestsPage/__tests__/RequestsPage.test..js
  src/views/RequestsPage/__tests__/RequestsPage.test.js
Labels: completed

#49 #159725777 Implement request details modal
  .gitignore
  package.json
  src/components/RequestsModal/CommentBox/CommentBox.jsx
  src/components/RequestsModal/CommentBox/_CommentBox.scss
  src/components/RequestsModal/CommentBox/__test__/CommentBox.test.js
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/RequestsModal.scss
  src/components/RequestsModal/_RequestTravel.jsx
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Table/Table.scss
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/image-link/__tests__/ImageLink.test.js
  src/components/modal/Modal.jsx
  src/components/modal/__tests__/__snapshots__/Modal.test.jsx.snap
  src/components/modal/_modal.scss
  src/components/nav-bar/NavBar.jsx
  src/components/nav-bar/__tests__/NavBar.test.js
  src/images/Oval.png
  src/images/Oval2.png
  src/routes/index.js
  src/views/RequestsPage/RequestsPage.jsx
  yarn.lock
Labels: completed

#43 #159725850 Consume api to post a new request
  package.json
  src/components/ApprovalsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
  src/components/Forms/FormsAPI/FormContext/FormContext.jsx
  src/components/Forms/FormsAPI/Input/__tests__/__snapshots__/index.test.jsx.snap
  src/components/Forms/FormsAPI/Input/__tests__/index.test.jsx
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/inputLabels.js
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewRequestForm/__tests__/__snapshots__/NewRequestForm.test.jsx.snap
  src/components/PageHeader/index.jsx
  src/components/Pagination/_pagination.scss
  src/components/RequestPanelHeader/RequestPanelHeader.jsx
  src/components/RequestPanelHeader/__tests__/RequestsPanelHeader.test.js
  src/components/RequestPanelHeader/__tests__/__snapshots__/RequestsPanelHeader.test.js.snap
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/Table/Table.scss
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/modal/Modal.jsx
  src/components/modal/__tests__/Modal.test.jsx
  src/components/modal/__tests__/__snapshots__/Modal.test.jsx.snap
  src/components/nav-bar/__tests__/NavBar.test.js
  src/hoc/authHoc.js
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/__tests__/modalActions.test.js
  src/redux/actionCreator/__tests__/requestActions.test.js
  src/redux/actionCreator/index.js
  src/redux/actionCreator/modalActions.js
  src/redux/actionCreator/requestActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/requestsSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/requestsSaga.js
  src/redux/reducers/__tests__/modals.test.js
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/index.js
  src/redux/reducers/modal.js
  src/redux/reducers/requests.js
  src/services/RequestAPI.js
  src/services/__tests__/RequestAPI.test.js
  src/services/__tests__/apiErrorHandler.test.js
  src/services/apiErrorHandler.js
  src/views/App/__tests__/Request.test.js
  src/views/App/__tests__/__snapshots__/Request.test.js.snap
  src/views/Base/index.jsx
  src/views/RequestsPage/RequestsPage.jsx
  src/views/RequestsPage/__tests__/RequestsPage.test.js
  src/views/RequestsPage/__tests__/__snapshots__/RequestsPage.test.js.snap
Labels: ready

#58 #160086204 Fix Request Dropdown
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItem/LeftSideNavItem.jsx
Labels: ready

#61 #160046067 Add Name Column To Approval Table
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/Table/index.jsx
Labels: ready

#66 #160124779 Make notification pane toggle
  src/components/notification-pane/__tests__/NotificationPane.test.js
  src/views/ApprovalsPage/index.jsx
  src/views/Base/index.jsx
  src/views/RequestsPage/RequestsPage.jsx
  src/views/RequestsPage/__tests__/RequestsPage.test.js
Labels: ready

#65 #160141144 Update SideDrawer on mobile screen
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/SideDrawer/SideDrawer.jsx
  src/components/SideDrawer/SideDrawer.test.js
  src/components/SideDrawer/__tests__
  src/components/SideDrawer/__tests__/SideDrawer.test.js
  src/views/Base/index.jsx
  src/views/RequestsPage/__tests__/__snapshots__/RequestsPage.test.js.snap
Labels: ready

#70 #160096049 Fix open requests count
  src/components/ApprovalsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
  src/components/Pagination/HeaderPagination.jsx
  src/components/Pagination/Pagination.jsx
  src/components/Pagination/__tests__/Pagination.test.js
  src/components/RequestPanelHeader/RequestPanelHeader.jsx
  src/components/RequestPanelHeader/__tests__/RequestsPanelHeader.test.js
  src/components/RequestPanelHeader/__tests__/__snapshots__/RequestsPanelHeader.test.js.snap
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/SelectDropDown/SelectDropDown.jsx
  src/components/SelectDropDown/__tests__/SelectDropDown.test.js
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/TextLink/__tests__/TextLink.test.js
  src/components/button-group/ButtonGroup.jsx
  src/components/button-group/__tests__/ButtonGroup.tests.js
  src/components/modal/Modal.jsx
  src/components/modal/overlay/Overlay.jsx
  src/helper/Utils.js
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/__tests__/requestActions.test.js
  src/redux/actionCreator/requestActions.js
  src/redux/middleware/__tests__/requestsSaga.test.js
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/requests.js
  src/services/RequestAPI.js
  src/services/__mocks__/mocks.js
  src/services/__tests__/RequestAPI.test.js
  src/services/__tests__/apiErrorHandler.test.js
  src/services/apiErrorHandler.js
  src/views/App/__tests__/Request.test.js
  src/views/App/__tests__/__snapshots__/Request.test.js.snap
  src/views/ApprovalsPage/__tests__/ApprovalsPage.test.js
  src/views/RequestsPage/RequestsPage.jsx
  src/views/RequestsPage/__tests__/RequestsPage.test.js
  src/views/RequestsPage/__tests__/__snapshots__/RequestsPage.test.js.snap
Labels: ready

#69 #160106281 Fix text editor bug
  src/components/RequestsModal/CommentBox/CommentBox.jsx
  src/components/RequestsModal/CommentBox/_CommentBox.scss
  src/components/RequestsModal/CommentBox/__test__/CommentBox.test.js
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/modal/_modal.scss
Labels: ready

#71 #160146026 Fix approval page table
  src/components/Pagination/_pagination.scss
  src/components/RequestPanelHeader/Request.scss
  src/components/RequestsModal/CommentBox/__test__/__snapshots__/CommentBox.test.js.snap
  src/components/Table/Table.scss
  src/components/Table/index.jsx
  src/components/button-group/buttonGroup.scss
  src/components/nav-bar/NavBar.jsx
  src/components/nav-bar/NavBar.scss
  src/components/nav-bar/__tests__/__snapshots__/NavBar.test.js.snap
  src/components/notification-pane/_notificationPane.scss
  src/components/search-bar/SearchBar.scss
  src/images/travela-mobile.svg
  src/index.scss
  src/views/Base/index.jsx
  src/views/RequestsPage/RequestsPage.scss
Labels: ready
