Repository andela/travel_tool_front, pull requests merged in 2018-10, with the labels that each got.

#165 #160725781 Clear Request Details Modal
  src/redux/reducers/requests.js
Labels: ready

#163 #160848557 Modify delete comment dialog
  src/components/RequestsModal/ConfirmDialog/ConfirmDialog.scss
  src/components/RequestsModal/UserComments/UserComments.scss
  src/components/RequestsModal/UserInfo/UserInfo.jsx
Labels: ready

#162 #160833565 Notifications for rejected requests
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/notification-pane/NotificationContainer.jsx
  src/customStyles/toast.scss
  src/helper/socket/socket.js
  src/views/App/index.jsx
Labels: ready

#140 #160370620 Edit Users Trip Request
  src/components/Forms/FormsAPI/Input/InputFields/HtmlInput.jsx
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/RadioButton/__test__/__snapshots__/RaidoButton.test.js.snap
  src/components/RadioButton/index.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/UserInfo/__tests__/__snapshots__/UserInfo.test.js.snap
  src/components/Table/Table.scss
  src/components/Table/index.jsx
  src/components/TableMenu/TableMenu.jsx
  src/components/TableMenu/TableMenu.scss
  src/components/TableMenu/__tests__/TableMenu.test.jsx
  src/components/nav-bar/__tests__/NavBar.test.js
  src/redux/actionCreator/requestActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/requestsSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/requestsSaga.js
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/requests.js
  src/services/RequestAPI.js
  src/services/__tests__/RequestAPI.test.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
Labels: ready

#156 #160710722 Enable travel admin view all created guest house centres
  package.json
  src/components/CentreGrid/CentreCard.jsx
  src/components/CentreGrid/CentreCard.scss
  src/components/CentreGrid/CentreGrid.scss
  src/components/CentreGrid/__tests__/CentreCard.test.js
  src/components/CentreGrid/__tests__/CentreGrid.test.js
  src/components/CentreGrid/__tests__/__snapshots__/CentreCard.test.js.snap
  src/components/CentreGrid/__tests__/__snapshots__/CentreGrid.test.js.snap
  src/components/CentreGrid/index.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/LeftSideBar/Metadata/index.js
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/helper/Utils.js
  src/images/default-image.jpg
  src/images/icons/accommodation-blue.svg
  src/images/icons/accomodation-grey.svg
  src/images/icons/hot_tub_24px.svg
  src/redux/actionCreator/__tests__/accommodationActions.test.js
  src/redux/actionCreator/accommodationActions.js
  src/redux/actionCreator/commentsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/accommodationSaga.js
  src/redux/middleware/__tests__/userAuthSagas.test.js
  src/redux/middleware/accommodationSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/accommodation.test.js
  src/redux/reducers/accommodation.js
  src/redux/reducers/index.js
  src/routes/index.js
  src/services/AccommodationAPI.js
  src/services/__tests__/AccommodationAPI.test.js
  src/views/Accommodation/__mocks__/mockData/guestHouses.js
  src/views/Accommodation/__tests__/Accommodation.test.js
  src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
  src/views/Accommodation/index.jsx
  src/views/Requests/index.jsx
  yarn.lock
Labels: ready

#169 #160951982 Fix error when checkbox clicked
  src/components/CheckBox/index.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/views/Requests/index.jsx
Labels: ready

#167 #160815252 Mark single notification as read
  src/components/Table/index.jsx
  src/components/nav-bar/NavBar.jsx
  src/components/notification-pane/NotificationContainer.jsx
  src/components/notification-pane/NotificationItem.jsx
  src/components/notification-pane/NotificationPane.jsx
  src/components/notification-pane/__tests__/NotificationItem.test.js
  src/components/notification-pane/__tests__/NotificationPane.test.js
  src/components/search-bar/__tests__/SearchBar.test.js
  src/redux/__mocks__/notificationsMockData.js
  src/redux/actionCreator/__tests__/notificationsActions.test.js
  src/redux/actionCreator/notificationsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/commentsSaga.test.js
  src/redux/middleware/__tests__/notificationsSaga.test.js
  src/redux/middleware/__tests__/requestsSaga.test.js
  src/redux/middleware/__tests__/userDataSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/notificationsSaga.js
  src/redux/reducers/__tests__/notifications.test.js
  src/redux/reducers/notifications.js
  src/services/NotificationsAPI.js
Labels: ready

#173 #160815252 Fix notification prop-type warnings
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewRequestForm/__tests__/PersonalDetailsFieldset.test.jsx
  src/components/Forms/NewUserRoleForm/__test__/NewUserRoleForm.test.js
  src/components/Hoc/__tests__/withLoading.test.js
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/notification-pane/NotificationItem.jsx
  src/components/notification-pane/__tests__/NotificationContainer.test.js
  src/components/notification-pane/__tests__/NotificationItem.test.js
  src/views/Approvals/__tests__/Approvals.test.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
Labels: ready

#166 #160833193 Include Profile Drop Down To Navigation Bar
  src/components/nav-bar/NavBar.jsx
  src/components/nav-bar/NavBar.scss
  src/components/nav-bar/__tests__/NavBar.test.js
  src/components/nav-bar/__tests__/__snapshots__/NavBar.test.js.snap
  src/images/account_circle.svg
  src/images/logout.svg
Labels: ready

#175 #160989966 Display requester avatar on approve-request modal
  src/components/RequestsModal/UserInfo/UserInfo.jsx
Labels: ready

#168 #160715616 Check in to guesthouse
  src/components/CheckInTable/CheckInTable.scss
  src/components/CheckInTable/__tests__/CheckInTable.test.js
  src/components/CheckInTable/__tests__/__snapshots__/CheckInTable.test.js.snap
  src/components/CheckInTable/index.jsx
  src/components/LeftSideBar/LeftSideNavItems/__tests__/__snapshots__/LeftSideNavItems.test.jsx.snap
  src/components/LeftSideBar/Metadata/index.js
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/helper/Utils.js
  src/images/icons/accommodation-blue.svg
  src/images/icons/accomodation-grey.svg
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/__tests__/tripActions.test.js
  src/redux/actionCreator/tripActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/tripsSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/tripsSaga.js
  src/redux/reducers/__tests__/trips.test.js
  src/redux/reducers/index.js
  src/redux/reducers/trips.js
  src/routes/index.js
  src/services/TripsAPI.js
  src/services/__mocks__/serviceMocks.js
  src/services/__tests__/TripsAPI.test.js
  src/views/CheckIn/__tests__/CheckIn.test.js
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/CheckIn/index.jsx
Labels: ready

#172 #160982898 Rearrange Column Position For Destination and Origin
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/notification-pane/NotificationItem.jsx
Labels: ready

#161 #160710724 Enable Travel Administrator to View Further Guest House Details
  .env.example
  src/components/CentreGrid/CentreCard.jsx
  src/components/CentreGrid/__tests__/CentreGrid.test.js
  src/components/CentreGrid/__tests__/__snapshots__/CentreCard.test.js.snap
  src/components/CentreGrid/__tests__/__snapshots__/CentreGrid.test.js.snap
  src/components/CentreGrid/index.jsx
  src/components/GuestHouseDetailCard/GuestHouseDetailCard.scss
  src/components/GuestHouseDetailCard/index.jsx
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItems.jsx
  src/components/LeftSideBar/Metadata/index.js
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/RequestsModal/UserInfo/__tests__/__snapshots__/UserInfo.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/index.jsx
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/RoomGeomWrapper.scss
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/index.jsx
  src/components/Timeline/RoomsGeomWrapper/RoomsGeomWrapper.scss
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/TripDetails.scss
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/index.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripGeomHelper.js
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripGeometry.scss
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/index.jsx
  src/components/Timeline/RoomsGeomWrapper/index.jsx
  src/components/Timeline/Timeline.scss
  src/components/Timeline/TimelineHeader/ArrowIcon.jsx
  src/components/Timeline/TimelineHeader/TimelineHeader.scss
  src/components/Timeline/TimelineHeader/index.jsx
  src/components/Timeline/TimelineVerticalAxis/RoomLabel.jsx
  src/components/Timeline/TimelineVerticalAxis/TimelineVerticalAxis.scss
  src/components/Timeline/TimelineVerticalAxis/index.jsx
  src/components/Timeline/helpers.js
  src/components/Timeline/index.jsx
  src/components/Timeline/settings.js
  src/components/nav-bar/NavBar.jsx
  src/components/nav-bar/__tests__/__snapshots__/NavBar.test.js.snap
  src/hoc/Layout/__tests__/Layout.test.jsx
  src/images/icons/accomodation_active.svg
  src/images/icons/accomodation_inactive.svg
  src/redux/actionCreator/accommodationActions.js
  src/redux/actionCreator/accomodationActions.js
  src/redux/actionCreator/index.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/accommodationSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/accommodation.test.js
  src/redux/reducers/accommodation.js
  src/routes/index.js
  src/services/AccommodationAPI.js
  src/services/mockData.js
  src/views/Accommodation/FullGuestHouseDetails/FullGuestHouseDetails.scss
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/GuestHouses/index.jsx
  yarn.lock
Labels: ready

#150 #160710730 Mark room as faulty
  package.json
  src/components/CheckBox/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/index.jsx
  src/components/Timeline/RoomsGeomWrapper/index.jsx
  src/components/Timeline/TimelineVerticalAxis/RoomLabel.jsx
  src/components/Timeline/TimelineVerticalAxis/TimelineVerticalAxis.scss
  src/components/Timeline/TimelineVerticalAxis/index.jsx
  src/components/Timeline/index.jsx
  src/components/notification-pane/__mocks__/notificationMockData.js
  src/mockData/guestRoom.js
  src/redux/actionCreator/__tests__/roomAction.test.js
  src/redux/actionCreator/accomodationActions.js
  src/redux/actionCreator/roomActionCreator.js
  src/redux/actionCreator/userProfileActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/accomodationSaga.js
  src/redux/middleware/index.js
  src/redux/middleware/roomUpdateSaga.js
  src/redux/reducers/__tests__/room.test.js
  src/redux/reducers/index.js
  src/redux/reducers/requests.js
  src/redux/reducers/room.js
  src/services/RoomApi.js
  src/services/accomodationApi.js
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/GuestHouses/index.jsx
Labels: ready

#171 # 160710694 Create guest house
  .env.example
  .hello.txy.swp
  docker/dev/.Dockerfile.swp
  src/components/AccommodationPanelHeader/AccommodationPanelHeader.scss
  src/components/AccommodationPanelHeader/__tests__/AccommodationPanelHeader.test.js
  src/components/AccommodationPanelHeader/index.jsx
  src/components/CentreGrid/__tests__/.CentreGrid.test.js.swp
  src/components/CentreGrid/__tests__/CentreGrid.test.js
  src/components/CentreGrid/__tests__/__snapshots__/CentreGrid.test.js.snap
  src/components/CentreGrid/index.jsx
  src/components/Forms/FormsAPI/Input/InputFields/DropdownSelect.jsx
  src/components/Forms/FormsAPI/Input/InputFields/NumberInput.jsx
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/HtmlInput.test.jsx
  src/components/Forms/FormsAPI/Input/InputFields/index.js
  src/components/Forms/FormsAPI/Input/_input.scss
  src/components/Forms/FormsAPI/Input/index.jsx
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/FormsMetadata/NewAccommodationForm/dropdownSelectOptions.js
  src/components/Forms/FormsMetadata/NewAccommodationForm/index.js
  src/components/Forms/FormsMetadata/NewAccommodationForm/inputLabels.js
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/dropdownSelectOptions.js
  src/components/Forms/NewAccommodationForm/FormFieldsets/AccommodationDetails.jsx
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
  src/components/Forms/NewAccommodationForm/NewAccommodation.scss
  src/components/Forms/NewAccommodationForm/__tests__/NewAccommodation.tests.js
  src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/index.js
  src/components/LeftSideBar/Metadata/index.js
  src/helper/toast.js
  src/helper/userDetails.js
  src/images/accommodation.svg
  src/images/add_photo_alternate_24px.svg
  src/redux/__mocks__/AccommodationData.js
  src/redux/actionCreator/__tests__/createAccommodationActions.test.js
  src/redux/actionCreator/accommodationActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/createAccommodationSaga.test.js
  src/redux/middleware/accommodationSaga.js
  src/redux/middleware/index.js
  src/redux/middleware/requestsSaga.js
  src/redux/reducers/__tests__/accommodation.test.js
  src/redux/reducers/__tests__/approvals.test.js
  src/redux/reducers/__tests__/createAccommodation.test.js
  src/redux/reducers/accommodation.js
  src/services/AccommodationAPI.js
  src/views/Accommodation/Accommodation.scss
  src/views/Accommodation/__tests__/Accommodation.test.js
  src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
  src/views/Accommodation/index.jsx
  src/views/App/index.jsx
  src/views/Role/__tests__/Role.test.js
Labels: ready

#183 #160710694 Add environment variables
  .circleci/load_env_variables.sh
Labels: devops-review

#186 #160715637 Check out of guesthouse
  src/components/CheckInTable/CheckInTable.scss
  src/components/CheckInTable/index.jsx
  src/index.scss
  src/views/CheckIn/index.jsx
Labels: ready

#185 #160710842 Implement edit guest house centre functionality
  src/components/Forms/NewAccommodationForm/FormFieldsets/AccommodationDetails.jsx
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
  src/components/Forms/NewAccommodationForm/NewAccommodation.scss
  src/components/Forms/NewAccommodationForm/__tests__/NewAccommodation.tests.js
  src/components/Forms/NewRequestForm/FormFieldsets/SubmitArea.jsx
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/Timeline/Timeline.scss
  src/components/Timeline/TimelineHeader/TimelineHeader.scss
  src/components/Timeline/TimelineVerticalAxis/TimelineVerticalAxis.scss
  src/redux/actionCreator/accommodationActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/accommodationSaga.js
  src/redux/middleware/accommodationSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/accommodation.test.js
  src/redux/reducers/__tests__/createAccommodation.test.js
  src/redux/reducers/accommodation.js
  src/services/AccommodationAPI.js
  src/services/__tests__/AccommodationAPI.test.js
  src/services/accomodationApi.js
  src/views/Accommodation/FullGuestHouseDetails/FullGuestHouseDetails.scss
  src/views/Accommodation/FullGuestHouseDetails/__tests__/EditGuestHouseDetails.test.js
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/Accommodation/__mocks__/mockData/guestHouses.js
  src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
  src/views/Accommodation/index.jsx
Labels: ready

#190 #160710730 Update tests for marking room as faulty
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/Timeline/TimelineVerticalAxis/RoomLabel.jsx
  src/components/Timeline/TimelineVerticalAxis/_tests_/RoomLabelFaultStatus.test.js
  src/components/Timeline/TimelineVerticalAxis/_tests_/__snapshots__/RoomLabelFaultStatus.test.js.snap
  src/redux/middleware/__tests__/roomUpdateSaga.test.js
  src/redux/middleware/__tests__/userProfileSaga.test.js
  src/redux/middleware/roomUpdateSaga.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
Labels: ready

#191 #160813365 Fix Updated trips Table
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/redux/middleware/requestsSaga.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
Labels: ready

#196 #161117241 Fix save button remains disabled when creating a guest house
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
  src/redux/actionCreator/accomodationActions.js
  src/redux/middleware/accomodationSaga.js
Labels: ready

#187 #160710724 Pay Technical Debt for Full Guest House Details
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/buttonToggleOptions.js
  src/components/Forms/ProfileForm/FormFieldsets/ProfileDetails.jsx
  src/components/GuestHouseDetailCard/__tests__/GuestHouseDetailCard.test.jsx
  src/components/GuestHouseDetailCard/__tests__/__snapshots__/GuestHouseDetailCard.test.jsx.snap
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItem/LeftSideNavItem.jsx
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/BedGeomWrapper.test.jsx
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/RoomGeomWrapper.test.jsx
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/index.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/TripDetails.scss
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/__tests__/TripDetails.test.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/index.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripGeomHelper.js
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/TripGeomHelper.test.js
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/TripGeometry.test.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/index.jsx
  src/components/Timeline/RoomsGeomWrapper/__tests__/RoomsGeomWrapper.test.jsx
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/index.jsx
  src/components/Timeline/TimelineHeader/TimelineHeader.scss
  src/components/Timeline/TimelineHeader/__tests__/ArrowIcon.test.jsx
  src/components/Timeline/TimelineHeader/__tests__/TimelineHeader.test.jsx
  src/components/Timeline/TimelineHeader/__tests__/__snapshots__/ArrowIcon.test.jsx.snap
  src/components/Timeline/TimelineHeader/__tests__/__snapshots__/TimelineHeader.test.jsx.snap
  src/components/Timeline/TimelineHeader/index.jsx
  src/components/Timeline/TimelineVerticalAxis/RoomLabel.jsx
  src/components/Timeline/TimelineVerticalAxis/__tests__/RoomLabel.test.jsx
  src/components/Timeline/TimelineVerticalAxis/__tests__/TimelineVerticalAxis.test.jsx
  src/components/Timeline/TimelineVerticalAxis/__tests__/__snapshots__/RoomLabel.test.jsx.snap
  src/components/Timeline/TimelineVerticalAxis/__tests__/__snapshots__/TimelineVerticalAxis.test.jsx.snap
  src/components/Timeline/__tests__/Timeline.test.jsx
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/Timeline/index.jsx
  src/components/Timeline/settings.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/guestHouseDetailsSaga.test.js
  src/redux/middleware/accommodationSaga.js
  src/redux/reducers/__tests__/accommodation.test.js
  src/services/__tests__/AccommodationAPI.test.js
  src/services/mockData.js
  src/views/Accommodation/FullGuestHouseDetails/FullGuestHouseDetails.scss
  src/views/Accommodation/FullGuestHouseDetails/__tests__/FullGuestHouseDetails.test.jsx
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
Labels: ready

#155 #160714903 View accommodation details as part of request modal
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/RequestsModal.scss
  src/components/RequestsModal/TripDetails/__tests__/TripDetails.test.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/TripDetails/index.jsx
Labels: ready

#159 160525336 Filter role dropdown with roles from API
  src/components/Forms/FormsAPI/Input/InputFields/DropdownOptions.jsx
  src/components/Forms/FormsAPI/Input/InputFields/DropdownSelect.jsx
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/ButtonToggler.test.jsx
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/Date.test.jsx
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/DropdownSelect.test.jsx
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/ButtonToggler.test.jsx.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/DropdownSelect.test.jsx.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/filterDropdownSelect.test.jsx.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/filterDropdownSelect.test.jsx
  src/components/Forms/FormsAPI/Input/InputFields/filterDropdownSelect.jsx
  src/components/Forms/FormsAPI/Input/InputFields/index.js
  src/components/Forms/FormsAPI/Input/_input.scss
  src/components/Forms/FormsAPI/Input/index.jsx
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/FormsMetadata/NewProfileMetadata/dropdownSelect.js
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/dropdownSelectOptions.js
  src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/NewRequestForm/__tests__/PersonalDetailsFieldset.test.jsx
  src/components/Forms/NewUserRoleForm/__test__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/occupationActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/occupationSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/occupationSaga.js
  src/redux/reducers/__tests__/occupations.test.js
  src/redux/reducers/index.js
  src/redux/reducers/occupations.js
  src/services/OccupationAPI.js
  src/services/__mocks__/serviceMocks.js
  src/services/__tests__/occupationAPI.test.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/index.jsx
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
Labels: ready

#198 #161147524 Remove edit restriction of guest house centres
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
  src/components/Forms/NewAccommodationForm/__tests__/NewAccommodation.tests.js
  src/images/icons/edit_icon.svg
  src/services/__tests__/CommentsAPI.test.js
  src/views/Accommodation/FullGuestHouseDetails/FullGuestHouseDetails.scss
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
Labels: ready

#189 #161050094 Fix Redirect Link for Email Notification
  .gitignore
  src/components/Table/__tests__/Table.test.js
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/routes/index.js
  src/views/Login/__tests__/Login.test.js
  src/views/Login/index.jsx
Labels: ready

#206 #160718924 Add Mobile Responsiveness to the New Request Form
  src/components/Forms/FormsAPI/Input/_input.scss
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Timeline/TimelineHeader/TimelineHeader.scss
Labels: ready

#215 #161280035 Clean Up Environment Variables
  .circleci/load_env_variables.sh
  .circleci/utils.sh
Labels: devops-review

#216 #161280035 Export STATIC_IP Environment Variable
  .circleci/utils.sh
Labels: devops-review

#205 #161208596 FormsAPI Clean up & Documentation
  src/components/Forms/FormsAPI/FormContext/FormContext.jsx
  src/components/Forms/FormsAPI/Input/InputFields/ButtonToggler.jsx
  src/components/Forms/FormsAPI/Input/InputFields/Date.jsx
  src/components/Forms/FormsAPI/Input/InputFields/DropdownOptions.jsx
  src/components/Forms/FormsAPI/Input/InputFields/DropdownSelect.jsx
  src/components/Forms/FormsAPI/Input/InputFields/HtmlInput.jsx
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/FormsAPI/Input/InputFields/index.js
  src/components/Forms/FormsAPI/Input/__tests__/__snapshots__/index.test.jsx.snap
  src/components/Forms/FormsAPI/Input/index.jsx
  src/components/Forms/FormsAPI/README.md
  src/components/Forms/FormsAPI/formEventHandlers/__tests__/formEventHandlers.test.js
  src/components/Forms/FormsAPI/formEventHandlers/eventHandlerCreators.js
  src/components/Forms/FormsAPI/formEventHandlers/index.js
  src/components/Forms/FormsAPI/formValidator/index.js
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/NewAccommodationForm/FormFieldsets/AccommodationDetails.jsx
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewUserRoleForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewUserRoleForm/NewUserRoleForm.jsx
  src/components/Forms/NewUserRoleForm/__test__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/Forms/ProfileForm/FormFieldsets/ProfileDetails.jsx
  src/components/Forms/ProfileForm/index.jsx
  src/components/Forms/index.js
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
Labels: ready

#220 #160717378 Edit travel team member
  src/components/ApprovalsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/DropdownSelect.jsx
  src/components/Forms/FormsMetadata/NewUserRoleForm/inputLabels.js
  src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewUserRoleForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewUserRoleForm/NewUserRoleForm.jsx
  src/components/Forms/NewUserRoleForm/__test__/NewUserRoleForm.test.js
  src/components/Forms/NewUserRoleForm/__test__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/LeftSideBar/LeftSideBar.jsx
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItems.jsx
  src/components/LeftSideBar/Metadata/index.js
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/PageHeader/_header.scss
  src/components/PageHeader/index.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RoleDetailsTable/RoleDetailsTable.scss
  src/components/RoleDetailsTable/__tests__/RoleDetailsTable.test.js
  src/components/RoleDetailsTable/__tests__/__snapshots__/RoleDetailsTable.test.js.snap
  src/components/RoleDetailsTable/index.js
  src/components/RoleTable/index.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/modal/_modal.scss
  src/helper/Utils.js
  src/helper/permissions/index.js
  src/index.scss
  src/redux/actionCreator/__tests__/centersActions.test.js
  src/redux/actionCreator/centersActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/centersSaga.test.js
  src/redux/middleware/centersSaga.js
  src/redux/middleware/index.js
  src/redux/middleware/roleDataSaga.js
  src/redux/reducers/__tests__/centers.test.js
  src/redux/reducers/__tests__/role.test.js
  src/redux/reducers/__tests__/user.test.js
  src/redux/reducers/centers.js
  src/redux/reducers/index.js
  src/redux/reducers/role.js
  src/redux/reducers/user.js
  src/routes/index.js
  src/services/CentersAPI.js
  src/services/__tests__/CentersAPI.test.js
  src/views/Accommodation/Accommodation.scss
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/Accommodation/__tests__/Accommodation.test.js
  src/views/Accommodation/index.jsx
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/CheckIn/index.jsx
  src/views/Requests/index.jsx
  src/views/Role/Role.scss
  src/views/Role/__tests__/Role.test.js
  src/views/Role/index.jsx
  src/views/RoleDetails/RoleDetails.scss
  src/views/RoleDetails/__tests__/RoleDetails.test.js
  src/views/RoleDetails/__tests__/__snapshots__/RoleDetails.test.js.snap
  src/views/RoleDetails/index.js
Labels: ready

#219 #161176677 Fix Back Arrow Redirect to GuestHouse Details
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/modal/Modal.jsx
Labels: ready

#230 # 161342302 Correct typographical error
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/TripDetails/index.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/modal/__tests__/__snapshots__/Modal.test.jsx.snap
Labels: bug

#223 #160862631 Replace tinymce with another text editor
  package.json
  public/index.html
  src/components/RequestsModal/CommentBox/CommentBox.jsx
  src/components/RequestsModal/CommentBox/_CommentBox.scss
  src/components/RequestsModal/CommentBox/__tests__/CommentBox.test.js
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  yarn.lock
Labels: ready

#227 #160717378 Test for changing travel team member center
  src/components/Forms/NewUserRoleForm/__test__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/Forms/NewUserRoleForm/__tests__/NewUserRoleForm.test.js
  src/components/Forms/NewUserRoleForm/__tests__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/RoleDetailsTable/__tests__/RoleDetailsTable.test.js
  src/components/RoleDetailsTable/__tests__/__snapshots__/RoleDetailsTable.test.js.snap
  src/components/RoleDetailsTable/index.js
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/actionCreator/__tests__/centersActions.test.js
  src/redux/actionCreator/centersActions.js
  src/redux/middleware/__tests__/centersSaga.test.js
  src/redux/reducers/__tests__/centers.test.js
  src/services/__tests__/CentersAPI.test.js
  src/views/Role/__tests__/Role.test.js
  src/views/RoleDetails/__tests__/RoleDetails.test.js
Labels: PEER-REVIEW

#229 #161084713 Fix Checkbox on Personal Details section
  src/components/CheckBox/index.jsx
  src/components/CheckInTable/__tests__/__snapshots__/CheckInTable.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/DropdownSelect.jsx
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Forms/ProfileForm/_tests_/ProfileForm.test.jsx
  src/components/Forms/ProfileForm/index.jsx
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/CommentBox.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/helper/Utils.js
  src/redux/reducers/index.js
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
  src/views/UserProfile/__tests__/UserProfile.test.js
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
  src/views/UserProfile/index.jsx
  yarn.lock
Labels: PEER-REVIEW

#184 #160597069 Add guest room and bed during request
  package.json
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/dropdownSelectOptions.js
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/inputLabels.js
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetails.test.js
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/redux/actionCreator/__tests__/accommodationActions.test.js
  src/redux/actionCreator/__tests__/availableRoomsActions.test.js
  src/redux/actionCreator/availableRoomsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/accommodationSaga.test.js
  src/redux/middleware/__tests__/availableRoomsSaga.test.js
  src/redux/middleware/availableRoomsSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/availableRooms.test.js
  src/redux/reducers/availableRooms.js
  src/redux/reducers/index.js
  src/services/AvailableRoomsAPI.js
  src/services/__tests__/AccommodationAPI.test.js
  src/services/__tests__/AvailableRoomsAPI.test.js
  src/views/AvailableRooms/__mocks__/mockData/availableRooms.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
  yarn.lock
Labels: ready

#236 #161379518 Remove auto-suggestion on date fields
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewUserRoleForm/__tests__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
Labels: ready

#233 #161376806 Remove dummy approver data on request modal
  src/components/CheckBox/Checkbox.scss
  src/components/RequestsModal/CommentBox/RequestApproval.jsx
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/UserComments/UserComments.jsx
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/helper/generateDynamicTime.js
  src/redux/middleware/userDataSaga.js
  src/views/Checklist/index.scss
  src/views/Requests/index.jsx
Labels: ready

#237 #161345105 Delete travel team member
  package.json
  src/components/PageHeader/index.jsx
  src/components/RequestsModal/ConfirmDialog/__tests__/__snapshots__/ConfirmDialog.test.js.snap
  src/components/RequestsModal/UserComments/CommentItem.jsx
  src/components/RequestsModal/UserComments/__tests__/__snapshots__/CommentItem.test.js.snap
  src/components/RoleDetailsTable/RoleDetailsTable.scss
  src/components/RoleDetailsTable/__tests__/RoleDetailsTable.test.js
  src/components/RoleDetailsTable/__tests__/__snapshots__/RoleDetailsTable.test.js.snap
  src/components/RoleDetailsTable/index.js
  src/components/modal/Modal.jsx
  src/components/modal/__tests__/Modal.test.jsx
  src/redux/__mocks__/role.js
  src/redux/actionCreator/__tests__/roleActions.js
  src/redux/actionCreator/__tests__/roleActions.test.js
  src/redux/actionCreator/roleActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/roleSaga.test.js
  src/redux/middleware/__tests__/travelChecklistSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/roleSaga.js
  src/redux/reducers/__tests__/role.test.js
  src/redux/reducers/__tests__/travelChecklist.test.js
  src/redux/reducers/role.js
  src/services/RoleAPI.js
  src/services/__tests__/RoleAPI.test.js
  src/services/apiErrorHandler.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/RoleDetails/__tests__/RoleDetails.test.js
  src/views/RoleDetails/__tests__/__snapshots__/RoleDetails.test.js.snap
  src/views/RoleDetails/index.js
Labels: ready

#235 #161050888 View deleted checklist items
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/redux/actionCreator/travelChecklistActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/accommodationSaga.test.js
  src/redux/middleware/__tests__/travelChecklistSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/travelChecklistSaga.js
  src/redux/reducers/__tests__/travelChecklist.test.js
  src/redux/reducers/travelChecklist.js
  src/services/__tests__/travelChecklistAPI.test.js
  src/services/travelChecklistAPI.js
  src/views/Checklist/ChecklistTable.scss
  src/views/Checklist/__tests__/index.js
  src/views/Checklist/index.js
  src/views/Checklist/index.scss
Labels: ready

#238 #161376711 Modify Room Information
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
Labels: ready

#241 #161044598 Fix delete checklist item
  src/views/Checklist/__tests__/index.js
  src/views/Checklist/index.js
Labels: ready

#240 #161502437 Fix add new member modal
  src/components/PageHeader/index.jsx
  src/redux/reducers/__tests__/role.test.js
  src/redux/reducers/role.js
  src/views/RoleDetails/__tests__/RoleDetails.test.js
  src/views/RoleDetails/index.js
Labels: ready

#243 #161510204 Fix comment action buttons
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/RequestsModal.scss
Labels: ready

#245 #161376681 Change date header name
  src/components/Table/index.jsx
Labels: ready

#246 #161543073 Update deleted checklist items section
  src/redux/middleware/travelChecklistSaga.js
Labels: ready

#247 #161177585 Fix vacant spaces for guest house
  src/components/ApprovalsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/reducers/__tests__/travelChecklist.test.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/EditGuestHouseDetails.test.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/FullGuestHouseDetails.test.jsx
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/RoleDetails/__tests__/__snapshots__/RoleDetails.test.js.snap
  yarn.lock
Labels: ready

#249 #16156558 Fix unwanted pre-populated data on request modal
  src/components/RequestsModal/RequestsModal.jsx
Labels: ready

#250 #161564861 Fix confirmation dialog close button
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/ConfirmDialog/ConfirmDialog.jsx
  src/components/RequestsModal/ConfirmDialog/__tests__/ConfirmDialog.test.js
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
Labels: ready

#255 #161584429 Fix reconfirmation dialog for delete travel member
  src/components/RoleDetailsTable/RoleDetailsTable.scss
Labels: ready
