Repository andela/travel_tool_front, pull requests merged in 2018-12, with the labels that each got.

#364 #162152454 Delete or edit maintenance schedule
  src/components/Forms/MaintainanceForm/FormFieldsets/SubmitArea.jsx
  src/components/Forms/MaintainanceForm/FormFieldsets/maintaince.jsx
  src/components/Forms/MaintainanceForm/_tests_/MaintainanceForm.test.jsx
  src/components/Forms/MaintainanceForm/_tests_/__snapshots__/MaintainanceForm.test.jsx.snap
  src/components/Forms/MaintainanceForm/index.jsx
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/MaintenanceDetails/__tests__/MaintenanceDetails.test.js
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/MaintenanceDetails/__tests__/__snapshots__/MaintenanceDetails.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/MaintenanceDetails/index.jsx
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/RoomGeomWrapper.test.jsx
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/index.jsx
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/index.jsx
  src/components/Timeline/Timeline.scss
  src/components/Timeline/TimelineVerticalAxis/RoomLabel.jsx
  src/components/Timeline/TimelineVerticalAxis/__tests__/__snapshots__/RoomLabel.test.jsx.snap
  src/components/Timeline/TimelineVerticalAxis/_tests_/RoomLabelFaultStatus.test.js
  src/components/Timeline/TimelineVerticalAxis/_tests_/__snapshots__/RoomLabelFaultStatus.test.js.snap
  src/components/Timeline/TimelineVerticalAxis/index.jsx
  src/components/Timeline/__tests__/Timeline.test.jsx
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/Timeline/index.jsx
  src/redux/actionCreator/maintenanceAction.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/maintainenceSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/maintenanceSaga.js
  src/redux/reducers/__tests__/maintenance.test.js
  src/redux/reducers/index.js
  src/redux/reducers/maintenance.js
  src/services/MaintainaceApi.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
Labels: TC/TTL Review

#356 #162181277 add validation to check destination and origin and issue warning if same.
  src/components/AnalyticsReport/__tests__/__snapshots__/AnalyticsReport.test.js.snap
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/FormsAPI/formValidator/index.js
  src/components/Forms/NewAccommodationForm/__tests__/NewAccommodation.tests.js
  src/components/Forms/NewRequestForm/FormFieldsets/SubmitArea.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
Labels: TC/TTL Review

#366 #162197071 Super admin can edit user role
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/AddRoleForm/__tests__/AddRoleForm.test.js
  src/components/Forms/AddRoleForm/index.js
  src/components/Forms/MaintainanceForm/_tests_/__snapshots__/MaintainanceForm.test.jsx.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/RoleTable/__tests__/RoleTable.test.js
  src/components/RoleTable/index.jsx
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/TimelineVerticalAxis/__tests__/__snapshots__/RoomLabel.test.jsx.snap
  src/components/Timeline/TimelineVerticalAxis/_tests_/__snapshots__/RoomLabelFaultStatus.test.js.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/actionCreator/roleActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/roleDataSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/roleDataSaga.js
  src/redux/reducers/__tests__/role.test.js
  src/redux/reducers/role.js
  src/services/RoleAPI.js
  src/services/__tests__/RoleAPI.test.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap
  src/views/Role/index.jsx
Labels: TC/TTL Review

#372 #162310451 Fix bug on renaming a travel document.
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/TravelCalendar/index.jsx
  src/views/Documents/__tests__/index.test.js
  src/views/Documents/index.js
Labels: TC/TTL Review

#371 #161876890 User can create different request types(End-to-end test)
  .codeclimate.yml
  .gitignore
  cypress/integration/component/Requests/create-request.spec.js
  cypress/integration/component/Requests/request.spec.js
  cypress/integration/component/logout.spec.js
  cypress/support/commands.js
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
Labels: TC/TTL Review

#378 #162305445 Fix colour scheme in dashboard pie charts
  src/components/PieChartAnalytics/__tests__/PieChartAnalytics.test.js
  src/components/PieChartAnalytics/index.jsx
  src/views/Analytics/index.jsx
Labels: TC/TTL Review

#381 #162381911 Fix changeroom modal position
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/TripDetails.scss
Labels: TC/TTL Review

#380 #162378697 Fix error in date picker for unblocking rooms
  src/components/Forms/MaintainanceForm/FormFieldsets/maintaince.jsx
  src/components/Forms/MaintainanceForm/__tests__/MaintainanceForm.test.jsx
  src/components/Forms/MaintainanceForm/__tests__/__snapshots__/MaintainanceForm.test.jsx.snap
  src/components/Forms/MaintainanceForm/index.jsx
  src/components/Forms/MaintainanceForm/maintainance.scss
  src/components/Forms/index.scss
Labels: TC/TTL Review

#368 #162006041 Fix room dropdown input field
  src/components/Forms/FormsAPI/Input/InputFields/DropdownSelect.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
Labels: TC/TTL Review

#383 #162382135 Add hotel booking option
  src/components/Forms/ChangeBedForm/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
  src/components/RequestsModal/TripDetails/index.jsx
Labels: TC/TTL Review

#385 #162421358 Fix manager change on request approval bug
  src/components/Forms/NewRequestForm/FormFieldsets/SubmitArea.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
Labels: TC/TTL Review

#386 #162376432 Add component for displaying error messages
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/PieChartAnalytics/__tests__/__snapshots__/PieChartAnalytics.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/AnalyticsCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/ChartCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/RequestsPlaceholder.test.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelCalendarPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelReadinessPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TripsPerMonthPlaceholder.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/images/404-image.jpg
  src/images/travela-404.png
  src/routes/index.js
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/ErrorPages/NotFound/NotFound.scss
  src/views/ErrorPages/NotFound/index.jsx
  src/views/ErrorPages/NotFound/responsiveness.scss
  src/views/ErrorPages/__tests__/NotFound.test.jsx
  src/views/ErrorPages/index.js
Labels: TC/TTL Review

#384 #162305343 Disable and restore guesthouses
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/CentreGrid/CentreCard.jsx
  src/components/CentreGrid/CentreCard.scss
  src/components/CentreGrid/CentreGrid.scss
  src/components/CentreGrid/__tests__/CentreCard.test.js
  src/components/CentreGrid/__tests__/CentreGrid.test.js
  src/components/CentreGrid/__tests__/__snapshots__/CentreCard.test.js.snap
  src/components/CentreGrid/__tests__/__snapshots__/CentreGrid.test.js.snap
  src/components/CentreGrid/index.jsx
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/DropdownSelect.test.jsx.snap
  src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetailsItem.test.js.snap
  src/components/Forms/NewUserRoleForm/__tests__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/helper/accommodationReducer.js
  src/images/icons/disabled.svg
  src/redux/actionCreator/__tests__/accommodationActions.test.js
  src/redux/actionCreator/accommodationActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/accommodationSaga.test.js
  src/redux/middleware/accommodationSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/accommodation.test.js
  src/redux/reducers/__tests__/createAccommodation.test.js
  src/redux/reducers/accommodation.js
  src/services/AccommodationAPI.js
  src/services/__tests__/AccommodationAPI.test.js
  src/views/Accommodation/FullGuestHouseDetails/FullGuestHouseDetails.scss
  src/views/Accommodation/FullGuestHouseDetails/__tests__/FullGuestHouseDetails.test.jsx
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/Accommodation/__mocks__/mockData/disabledGuestHouses.js
  src/views/Accommodation/__tests__/Accommodation.test.js
  src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
  src/views/Accommodation/index.jsx
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
Labels: TC/TTL Review

#388 #162382329 Display progress bar on document upload
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/NewDocumentForm/NewDocumentForm.scss
  src/components/Forms/NewDocumentForm/__tests__/NewDocumentForm.test.js
  src/components/Forms/NewDocumentForm/__tests__/__snapshots__/NewDocumentForm.test.js.snap
  src/components/Forms/NewDocumentForm/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/AnalyticsCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/ChartCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/RequestsPlaceholder.test.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelCalendarPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelReadinessPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TripsPerMonthPlaceholder.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/Documents/index.js
Labels: TC/TTL Review

#390 #162382620 Disable user from viewing checklist items of their location when request is open
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelCheckList/index.jsx
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap
Labels: TC/TTL Review

#387 #162378763 Fix analytics card for unavailable rooms
  src/components/GuestHouseDetailCard/index.jsx
  src/components/Timeline/__tests__/Timeline.test.jsx
  src/components/Timeline/index.jsx
  src/views/Accommodation/FullGuestHouseDetails/__tests__/FullGuestHouseDetails.test.jsx
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
Labels: PEER-REVIEW

#392 #162126795 End to End tests for Manager can view right items on approvals page
  cypress/fixtures/approvals/approval.json
  cypress/integration/component/Approvals/approval.spec.js
Labels: TC/TTL Review

#397 #162576739 Remove the command that checks for vulnerabilities
  .circleci/config.yml
Labels: devops-review

#396 #162474402 Display proper 404 message when content does not exist is returned
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Placeholders/__tests__/__snapshots__/AnalyticsCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/ChartCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/RequestsPlaceholder.test.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelCalendarPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelReadinessPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TripsPerMonthPlaceholder.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/middleware/accommodationSaga.js
  src/redux/middleware/analyticsSaga.js
  src/redux/middleware/approvalsSaga.js
  src/redux/middleware/requestsSaga.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/EditGuestHouseDetails.test.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/FullGuestHouseDetails.test.jsx
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/Approvals/index.jsx
  src/views/ErrorPages/NotFound/index.jsx
  src/views/ErrorPages/__tests__/NotFound.test.jsx
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
  src/views/RoleDetails/index.js
  src/views/Verifications/index.jsx
  yarn.lock
Labels: TC/TTL Review

#394 #162369171 Add e2e test for guesthouse creation.
  cypress/fixtures/images/guesthouse.jpg
  cypress/integration/component/Accommodation.js/create-guesthouse.spec.js
Labels: TC/TTL Review

#376 #162378991 Generate .env for tests
  .circleci/config.yml
  .circleci/load_env_variables.sh
Labels: devops-review

#401 #162540377 Fix the delete modal bug
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/AnalyticsCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/ChartCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/RequestsPlaceholder.test.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelCalendarPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelReadinessPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TripsPerMonthPlaceholder.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/TableMenu/TableMenu.jsx
  src/components/TableMenu/__tests__/TableMenu.test.jsx
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/reducers/requests.js
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
Labels: TC/TTL Review

#393 #162305548 Modify date range pickers on the dashboard
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelCalendar/TravelCalendar.scss
  src/components/TravelCalendar/__tests__/TravelCalendar.test.js
  src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
  src/components/TravelCalendar/index.jsx
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
Labels: TC/TTL Review

#409 # 161968220 Adds cancel button to mobile navigation
  src/components/SideDrawer/SideDrawer.jsx
  src/components/SideDrawer/SideDrawer.scss
  src/components/SideDrawer/__tests__/SideDrawer.test.js
Labels: TC/TTL Review

#403 #162541358 Fix bugs with creating and disabling guesthouses
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/helper/accommodationReducer.js
  src/redux/actionCreator/accommodationActions.js
  src/redux/middleware/__tests__/accommodationSaga.test.js
  src/redux/middleware/accommodationSaga.js
  src/redux/reducers/__tests__/accommodation.test.js
  src/redux/reducers/accommodation.js
  src/views/Accommodation/Accommodation.scss
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
  src/views/Accommodation/index.jsx
Labels: TC/TTL Review

#404 #162124406 End to End tests for Pagination
  cypress/integration/component/Pagination/pagination-interactions.spec.js
  cypress/integration/component/Pagination/pagination.spec.js
Labels: TC/TTL Review

#411 #162604565 Fix bug with new request form crashing app
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
Labels: TC/TTL Review

#395 #162375484 Tests for adding a checklist item (e2e)
  cypress/integration/component/TravelChecklist/create-checklistItems.spec.js
  src/components/TravelCheckList/SubmissionItem.jsx
Labels: TC/TTL Review

#405 #162573849 Add accommodation option
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetailsItem.test.js
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/services/AvailableRoomsAPI.js
Labels: TC/TTL Review

#399 #162375845 Test to ensure that roles are enforced with Travela roles
  cypress/integration/component/UserRoles/assign-role.spec.js
  cypress/integration/component/UserRoles/user-role.spec.js
  cypress/support/commands.js
Labels: TC/TTL Review

#391 #162127512 Manager can approve or reject travel request (End-to_end-Test)
  cypress/integration/component/Approvals/approve-reject-request.spec.js
Labels: TC/TTL Review

#412 #162636747 A user can edit a guest house
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
Labels: TC/TTL Review

#407 #162122460 E2E: User can only edit an open request
  .gitignore
  cypress/integration/component/Requests/edit-request.spec.js
Labels: TC/TTL Review

#415 #162693432 Make sure application starts before running e2e tests
  Makefile
  docker/e2e-tests/Dockerfile-backend
  docker/e2e-tests/Dockerfile-frontend
  docker/e2e-tests/docker-compose.yml
Labels: devops-review

#418 #162698516 Fix accommodation dropdown inconsistency for one way trips
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
Labels: TC/TTL Review

#416 #162701432 Create residence content loaders
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/CentreGrid/__tests__/CentreGrid.test.js
  src/components/CentreGrid/index.jsx
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Placeholders/ResidencePlaceholder.js
  src/components/Placeholders/__tests__/ResidencePlaceholder.test.js
  src/components/Placeholders/__tests__/__snapshots__/ResidencePlaceholder.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap
  src/views/RoleDetails/__tests__/__snapshots__/RoleDetails.test.js.snap
Labels: TC/TTL Review

#422 #162711373 change ticket number to flight number
  src/components/TravelCheckList/SubmissionsUtils.jsx
Labels: TC/TTL Review

#420 #162640479 Fix position of the Add User Role Modal
  src/components/Timeline/Timeline.scss
  src/views/Role/Role.scss
  src/views/Role/index.jsx
  src/views/RoleDetails/RoleDetails.scss
  src/views/RoleDetails/index.js
Labels: TC/TTL Review

#424 #162728852 Fix dashboard components
  src/components/AnalyticsCard/index.scss
  src/components/AnalyticsReport/index.jsx
  src/components/TravelCalendar/index.jsx
  src/components/TravelReadiness/__tests__/travelReadiness.test.js
  src/components/TravelReadiness/index.jsx
Labels: TC/TTL Review

#426 #162726866 Ensure user role is checked before content loads
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/ProfileForm/_tests_/ProfileForm.test.jsx
  src/components/Forms/ProfileForm/index.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/helper/permissions/__tests__/permissions.test.js
  src/helper/permissions/index.js
  src/helper/roles.js
  src/hoc/Layout/__tests__/Layout.test.jsx
  src/hoc/Layout/__tests__/__snapshots__/Layout.test.jsx.snap
  src/hoc/Layout/index.jsx
  src/hoc/__tests__/__snapshots__/authHoc.test.js.snap
  src/hoc/authHoc.js
  src/routes/index.js
  src/views/Accommodation/index.jsx
  src/views/Approvals/index.jsx
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/Checklist/index.jsx
  src/views/Dashboard/__tests__/.test.js
  src/views/Dashboard/__tests__/Dashboard.test.js
  src/views/Dashboard/index.jsx
  src/views/Role/index.jsx
  src/views/RoleDetails/index.js
  src/views/UserProfile/index.jsx
  src/views/Verifications/index.jsx
Labels: TC/TTL Review

#427 #162755938 Fix the modal cancel button issues
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/Accommodation/__tests__/Accommodation.test.js
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/Requests/__tests__/Requests.test.js
Labels: TC/TTL Review

#428 #162756406 Fix prompting 404 page when fetching requests by id
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
  src/components/RequestsModal/RequestsModal.jsx
  src/components/Table/index.jsx
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/middleware/accommodationSaga.js
  src/redux/reducers/accommodation.js
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
  src/views/Approvals/index.jsx
  src/views/ErrorPages/NotFound/NotFound.scss
  src/views/ErrorPages/NotFound/index.jsx
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
  src/views/Verifications/index.jsx
Labels: TC/TTL Review

#425 #162711180 Fix accommodation option for Round Trips
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetailsItem.test.js
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/RequestsModal/RequestModalHelper.js
  src/components/RequestsModal/TripDetails/index.jsx
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/requests.js
Labels: TC/TTL Review
