Repository andela/travel_tool_front, pull requests merged in 2018-11, with the labels that each got.

#258 #161574495 Fix notification count issue
  src/components/notification-pane/NotificationContainer.jsx
  src/components/notification-pane/NotificationItem.jsx
  src/components/notification-pane/NotificationPane.jsx
  src/components/notification-pane/__tests__/NotificationContainer.test.js
  src/components/notification-pane/__tests__/NotificationItem.test.js
  src/redux/middleware/notificationsSaga.js
  src/redux/reducers/__tests__/notification.test.js
  src/redux/reducers/__tests__/notifications.test.js
  src/redux/reducers/notifications.js
Labels: ready

#252 #161583616 Fix redirect url on modal close
  src/components/ApprovalsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/modal/Modal.jsx
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
Labels: ready

#256 #161587535 Add responsiveness to comment deletion confirmation modal
  src/components/RequestsModal/RequestsModal.scss
  src/components/RequestsModal/UserComments/UserComments.scss
Labels: ready

#242 #161374570 Dashboard Analytics
  src/components/AnalyticsCard/__tests__/AnalyticsCard.test.js
  src/components/AnalyticsCard/__tests__/__snapshots__/AnalyticsCard.test.js.snap
  src/components/AnalyticsCard/index.jsx
  src/components/AnalyticsCard/index.scss
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/DashboardHeader/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TimelineDropdown/__tests__/TimelineDropdown.test.js
  src/components/TimelineDropdown/index.js
  src/images/icons/flight_land.svg
  src/images/icons/flight_takeoff.svg
  src/images/icons/pending_icon.svg
  src/redux/actionCreator/analyticsActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/analyticsSaga.test.js
  src/redux/middleware/analyticsSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/analytics.test.js
  src/redux/reducers/analytics.js
  src/services/AnalyticsAPI.js
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Analytics/__tests__/Analytics.test.js
  src/views/Analytics/index.jsx
  src/views/Analytics/index.scss
  src/views/Dashboard/DashboardContext/FilterContext.jsx
  src/views/Dashboard/DashboardContext/__tests__/FilterContext.test.js
  src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap
  src/views/Dashboard/__tests__/Dashboard.test.js
  src/views/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
  src/views/Dashboard/index.jsx
  yarn.lock
Labels: PEER-REVIEW

#263 #161646318 Bug fix on role select
  src/components/Forms/FormsAPI/Input/InputFields/filterDropdownSelect.jsx
Labels: ready

#259 #161374901 View travel readiness of potential travellers
  src/components/AnalyticsReport/__tests__/AnalyticsReport.test.js
  src/components/AnalyticsReport/__tests__/__snapshots__/AnalyticsReport.test.js.snap
  src/components/AnalyticsReport/index.jsx
  src/components/AnalyticsReport/index.scss
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/TravelReadiness/__mocks__/travelReadinessMockData.js
  src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
  src/components/TravelReadiness/__tests__/travelReadiness.test.js
  src/components/TravelReadiness/index.jsx
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/__tests__/travelReadinessActions.test.js
  src/redux/actionCreator/travelReadinessActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/travelReadinessSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/travelReadinessSaga.js
  src/redux/reducers/__tests__/readiness.test.js
  src/redux/reducers/index.js
  src/redux/reducers/readiness.js
  src/services/ReadinessAPI.js
  src/services/__mocks__/serviceMocks.js
  src/services/__tests__/ReadinessAPI.test.js
  src/views/Dashboard/__tests__/Dashboard.test.js
  src/views/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
  src/views/Dashboard/index.jsx
  yarn.lock
Labels: PEER-REVIEW

#261 #161583635 User profile page mobile responsiveness
  src/components/Forms/ProfileForm/FormFieldsets/ProfileDetails.jsx
  src/hoc/authHoc.js
  src/views/UserProfile/UserProfile.scss
Labels: ready

#265 Rectifies the font in Travel Readiness Component
  src/components/AnalyticsReport/__tests__/__snapshots__/AnalyticsReport.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
  src/components/TravelReadiness/index.jsx
Labels: ready

#239 #161374998 Create Dashboard Travel Calendar
  .eslintrc.json
  src/components/AnalyticsCard/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/TimelineDropdownCalendar/__tests__/TimelineDropdownCalendar.test.js
  src/components/TimelineDropdownCalendar/index.jsx
  src/components/TimelineDropdownCalendar/index.scss
  src/components/TravelCalendarDetails/__tests__/TravelCalendarDetails.test.js
  src/components/TravelCalendarDetails/__tests__/__snapshots__/TravelCalendarDetails.test.js.snap
  src/components/TravelCalendarDetails/index.jsx
  src/components/TravelCalendarDetails/index.scss
  src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
  src/helper/Utils.js
  src/images/downArrow.svg
  src/images/flightLand.svg
  src/images/flightTakeoff.svg
  src/images/upArrow.svg
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/__tests__/travelCalendarActions.test.js
  src/redux/actionCreator/index.js
  src/redux/actionCreator/travelCalendarActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/travelCalendarSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/travelCalendarSaga.js
  src/redux/reducers/__tests__/travelCalendar.test.js
  src/redux/reducers/index.js
  src/redux/reducers/travelCalendar.js
  src/services/TravelCalendarAPI.js
  src/services/__mocks__/serviceMocks.js
  src/views/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
  src/views/Dashboard/index.jsx
  src/views/TravelCalendar/TravelCalendar.scss
  src/views/TravelCalendar/__tests__/TravelCalendar.test.js
  src/views/TravelCalendar/index.jsx
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
  yarn.lock
Labels: PEER-REVIEW

#253 #161509243 Restore deleted travel checklist items
  src/components/Forms/DeleteRequestForm/DeleteRequestForm.js
  src/components/Forms/DeleteRequestForm/FormFieldsets/SubmitArea.js
  src/components/Forms/DeleteRequestForm/__tests__/DeleteRequestForm.test.js
  src/components/Forms/DeleteRequestForm/__tests__/__snapshots__/DeleteRequestForm.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/modal/RestoreChecklistModal/RestoreChecklistModal.js
  src/components/modal/RestoreChecklistModal/__tests__/RestoreChecklistModal.test.js
  src/components/modal/RestoreChecklistModal/__tests__/__snapshots__/RestoreChecklistModal.test.js.snap
  src/components/nav-bar/__mocks__/notificationMockData-navBar.js
  src/components/nav-bar/__tests__/NavBar.test.js
  src/components/notification-pane/__mocks__/notificationMockData-pane.js
  src/components/notification-pane/__tests__/NotificationPane.test.js
  src/redux/middleware/travelChecklistSaga.js
  src/views/Checklist/ChecklistTable.scss
  src/views/Checklist/__tests__/index.js
  src/views/Checklist/index.js
  src/views/Checklist/index.scss
  yarn.lock
Labels: ready

#276 #161774276 Copy yarn.lock before installing dependencies
  docker/dev/Dockerfile
Labels: devops-review

#283 #161755477 Fix checkbox misalignment
  src/components/CheckBox/Checkbox.scss
  src/components/CheckBox/index.jsx
Labels: ready

#284 #161755766 Fix dashboard redirect issue
  src/views/Dashboard/__tests__/Dashboard.test.js
  src/views/Dashboard/index.jsx
Labels: ready

#282 #161595806 view uploaded documents
  src/components/DocumentsHeader/DocumentsHeader.scss
  src/components/DocumentsHeader/__tests__/DocumentsHeader.test.js
  src/components/DocumentsHeader/index.jsx
  src/components/LeftSideBar/Metadata/index.js
  src/images/icons/documents-blue.svg
  src/images/icons/documents-grey.svg
  src/images/icons/file_icon.svg
  src/images/icons/img_icon.svg
  src/redux/__mocks__/mockDocumentResponse.js
  src/redux/actionCreator/__tests__/documentActions.test.js
  src/redux/actionCreator/documentActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/DocumentSaga.js
  src/redux/middleware/__tests__/documentSaga.test.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/documents.test.js
  src/redux/reducers/documents.js
  src/redux/reducers/index.js
  src/routes/index.js
  src/services/DocumentAPI.js
  src/services/__tests__/DocumentAPI.test.js
  src/views/Documents/DocumentItem.js
  src/views/Documents/DocumentTable.js
  src/views/Documents/Documents.scss
  src/views/Documents/__tests__/DocumentItem.test.js
  src/views/Documents/__tests__/DocumentTable.test.js
  src/views/Documents/__tests__/index.test.js
  src/views/Documents/index.js
Labels: ready

#280 #161595888 Rename travel documents
  src/components/DocumentTableMenu/__tests__/DocumentTableMenu.test.js
  src/components/DocumentTableMenu/index.jsx
  src/mockData/documentsMockData.js
  src/redux/actionCreator/__tests__/documentActions.test.js
  src/redux/actionCreator/documentActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/DocumentSaga.js
  src/redux/middleware/__tests__/documentSaga.test.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/documents.test.js
  src/redux/reducers/documents.js
  src/services/DocumentAPI.js
  src/services/__tests__/DocumentAPI.test.js
  src/services/apiErrorHandler.js
  src/views/Documents/DocumentItem.js
  src/views/Documents/DocumentTable.js
  src/views/Documents/Documents.scss
  src/views/Documents/__tests__/index.test.js
  src/views/Documents/index.js
Labels: ready

#278 #161595854 User can add a travel document
  src/components/CheckBox/__tests__/__snapshots__/Checkbox.test.js.snap
  src/components/DashboardHeader/__tests__/index.test.js
  src/components/DocumentTableMenu/__tests__/__snapshots__/DocumentTableMenu.test.js.snap
  src/components/DocumentsHeader/DocumentsHeader.scss
  src/components/Forms/NewDocumentForm/FormFieldSets/SubmitArea.jsx
  src/components/Forms/NewDocumentForm/NewDocumentForm.scss
  src/components/Forms/NewDocumentForm/__tests__/NewDocumentForm.test.js
  src/components/Forms/NewDocumentForm/__tests__/__snapshots__/NewDocumentForm.test.js.snap
  src/components/Forms/NewDocumentForm/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/LeftSideBar/LeftSideNavItems/__tests__/__snapshots__/LeftSideNavItems.test.jsx.snap
  src/components/LeftSideBar/Metadata/index.js
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/modal/RestoreChecklistModal/__tests__/__snapshots__/RestoreChecklistModal.test.js.snap
  src/images/icons/document-upload.svg
  src/redux/__mocks__/documentMockData.js
  src/redux/actionCreator/documentActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/DocumentSaga.js
  src/redux/middleware/__tests__/documentSaga.test.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/documents.test.js
  src/redux/reducers/documents.js
  src/services/DocumentAPI.js
  src/services/__tests__/DocumentAPI.test.js
  src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap
  src/views/Documents/__tests__/index.test.js
  src/views/Documents/index.js
Labels: ready

#289 #161744068 Fix guest room change issue
  src/services/apiErrorHandler.js
Labels: ready

#279 # 161724530 Refactor code and improve test coverage
  src/components/AnalyticsCard/index.scss
  src/components/AnalyticsReport/__tests__/AnalyticsReport.test.js
  src/components/AnalyticsReport/__tests__/__snapshots__/AnalyticsReport.test.js.snap
  src/components/AnalyticsReport/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
  src/components/TravelReadiness/__tests__/travelReadiness.test.js
  src/components/TravelReadiness/index.jsx
  src/components/button-group/__tests__/__snapshots__/ButtonGroup.tests.js.snap
  src/components/buttons/Buttons.jsx
  src/components/nav-bar/__tests__/__snapshots__/NavBar.test.js.snap
  src/redux/actionCreator/__tests__/travelReadinessActions.test.js
  src/redux/actionCreator/travelReadinessActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/travelReadinessSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/travelReadinessSaga.js
  src/redux/reducers/__tests__/readiness.test.js
  src/redux/reducers/readiness.js
  src/services/ReadinessAPI.js
  src/services/__tests__/ReadinessAPI.test.js
  src/views/Dashboard/index.jsx
Labels: ready

#288 #161581971 Add guesthouse modal mobile responsiveness
  src/components/Forms/NewAccommodationForm/NewAccommodation.scss
  src/components/Forms/NewAccommodationForm/_NewAccommodation-largeMobileScreen.scss
  src/components/Forms/NewAccommodationForm/_NewAccommodation-mediumMobileScreen.scss
  src/components/Forms/NewAccommodationForm/_NewAccommodation-smallMobileScreen.scss
  src/components/Forms/NewAccommodationForm/_NewAccommodation-tablet.scss
  yarn.lock
Labels: ready

#232 #161044953 User can plan for an approved trip
  src/components/Forms/index.js
  src/components/Table/Table.scss
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/TableMenu/TableMenu.jsx
  src/components/TableMenu/__tests__/TableMenu.test.jsx
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelCheckList/CheckListSubmissionForm.jsx
  src/components/TravelCheckList/SubmissionFormSets.jsx
  src/components/TravelCheckList/__tests__/CheckListSubmissionForm.tests.js
  src/components/TravelCheckList/__tests__/SubmissionFormSets.tests.js
  src/components/TravelCheckList/travelChecklistMockData.js
  src/components/TravelCheckList/travelSubmission.scss
  src/components/modal/overlay/_overlay.scss
  src/helper/countryUtils.js
  src/images/check.svg
  src/images/saveIcon.svg
  src/images/uploadIcon.svg
  src/redux/actionCreator/checkListSubmissionActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/checklistSubmissionSaga.test.js
  src/redux/middleware/checklistSubmissionSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/submission.test.js
  src/redux/reducers/checklistSubmission.js
  src/redux/reducers/index.js
  src/services/__tests__/submissionAPI.test.js
  src/services/checklistSubmissionAPI.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
Labels: ready

#292 #161759224 Rename instances of the word delete to disable
  src/components/Forms/DeleteRequestForm/DeleteRequestForm.js
  src/components/Forms/DeleteRequestForm/FormFieldsets/SubmitArea.js
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/views/Checklist/__tests__/index.js
  src/views/Checklist/index.js
  src/views/Checklist/index.scss
Labels: ready

#277 #161646967 Fix yarn version inconsistency
  .circleci/config.yml
  docker/dev/Dockerfile
  package.json
  yarn.lock
Labels: ready

#297 #161581971 Implement image styling
  src/components/Forms/NewAccommodationForm/NewAccommodation.scss
  src/components/Forms/NewAccommodationForm/_NewAccommodation-largeMobileScreen.scss
  src/components/Forms/NewAccommodationForm/_NewAccommodation-mediumMobileScreen.scss
  src/components/Forms/NewAccommodationForm/_NewAccommodation-smallMobileScreen.scss
  src/components/Forms/NewAccommodationForm/_NewAccommodation-tablet.scss
Labels: PEER-REVIEW

#286 #161582665 Mobile responsive for trip planner page
  src/components/CheckInTable/CheckInTable.scss
  src/components/Forms/NewDocumentForm/NewDocumentForm.scss
  src/components/Forms/NewDocumentForm/responsiveness.scss
  src/components/LeftSideBar/_leftSideBar.scss
  src/components/LeftSideBar/responsiveness.scss
  src/components/PageHeader/_header.scss
  src/components/PageHeader/responsiveness.scss
  src/components/RequestPanelHeader/Request.scss
  src/components/RequestPanelHeader/responsiveness.scss
  src/components/RolePanelHeader/RolePanelHeader.scss
  src/components/RolePanelHeader/responsiveness.scss
  src/components/Table/Table.scss
  src/components/modal/_modal.scss
  src/hoc/Layout/Layout.scss
  src/hoc/Layout/responsiveness.scss
  src/index.scss
  src/responsiveness.scss
  src/views/Checklist/index.scss
  src/views/Checklist/responsiveness.scss
Labels: ready

#299 #161866839 Change submit comment button label
  src/components/RequestsModal/CommentBox/CommentBox.jsx
Labels: ready

#301 #161866832 Change request modal field label
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/inputLabels.js
Labels: ready

#300 #161889373 Set name of deleted travel team member in toast message
  src/components/RoleDetailsTable/index.js
  src/redux/actionCreator/__tests__/roleActions.test.js
  src/redux/actionCreator/roleActions.js
  src/redux/middleware/__tests__/roleSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/roleSaga.js
  src/views/Checklist/index.js
  src/views/RoleDetails/index.js
Labels: ready

#296 #161759544 Add loader component on trip planner page
  src/components/Preloader/Preloader.jsx
  src/components/Preloader/Preloader.scss
  src/views/Checklist/__tests__/index.js
  src/views/Checklist/index.js
  src/views/Checklist/index.scss
Labels: ready

#304 #161889102 Disable delete button for delete checklist Item
  src/components/Forms/DeleteRequestForm/DeleteRequestForm.js
  src/components/Forms/DeleteRequestForm/FormFieldsets/SubmitArea.js
  src/views/Checklist/index.js
  src/views/Checklist/index.scss
Labels: ready

#293 #161778452 Hide bed space column when trip is oneWay
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetails.test.js
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/Preloader/__tests__/__snapshots__/Preloader.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/CommentBox.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  yarn.lock
Labels: ready

#308 #161916799 Rearrange display order for posted comments
  src/components/RequestsModal/RequestsModal.jsx
  src/redux/reducers/requests.js
Labels: ready

#291 #161045193 Enable travel admin change requester room
  src/components/notification-pane/NotificationContainer.jsx
Labels: ready

#305 #161758633 Disable change room if user is checked out
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/index.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
Labels: ready

#313 #161979747 Restrict React/React-dom versions to ~16.5.1
  package.json
  yarn.lock
Labels: PEER-REVIEW

#309 #161690447 Render a conditional loader component
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/GuestHouseDetailCard/GuestHouseDetailCard.scss
  src/components/GuestHouseDetailCard/__tests__/__snapshots__/GuestHouseDetailCard.test.jsx.snap
  src/components/GuestHouseDetailCard/index.jsx
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/reducers/__tests__/accommodation.test.js
  src/redux/reducers/accommodation.js
  src/views/Accommodation/FullGuestHouseDetails/FullGuestHouseDetails.scss
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/index.jsx
Labels: ready

#274 #161374998 Refactor Travel Calendar
  package.json
  src/components/CalendarRange/index.jsx
  src/components/TimelineDropdownCalendar/__tests__/TimelineDropdownCalendar.test.js
  src/components/TimelineDropdownCalendar/index.jsx
  src/components/TimelineDropdownCalendar/index.scss
  src/components/TravelCalendar/TravelCalendar.scss
  src/components/TravelCalendar/__tests__/TravelCalendar.test.js
  src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
  src/components/TravelCalendar/index.jsx
  src/components/TravelCalendarDetails/__tests__/TravelCalendarDetails.test.js
  src/components/TravelCalendarDetails/index.jsx
  src/components/TravelCalendarDetails/index.scss
  src/helper/Utils.js
  src/helper/constants.js
  src/redux/__mocks__/mocks.js
  src/redux/actionCreator/__tests__/travelCalendarActions.test.js
  src/redux/actionCreator/index.js
  src/redux/actionCreator/travelCalendarActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/travelCalendarSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/travelCalendarSaga.js
  src/redux/reducers/__tests__/travelCalendar.test.js
  src/redux/reducers/travelCalendar.js
  src/services/TravelCalendarAPI.js
  src/services/__tests__/TravelCalendarAPI.test.js
  src/views/Dashboard/__tests__/Dashboard.test.js
  src/views/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
  src/views/Dashboard/index.jsx
  src/views/TravelCalendar/__tests__/TravelCalendar.test.js
  src/views/TravelCalendar/index.jsx
Labels: ready

#315 #161975169 Change badge on the request modal upon approval
  src/components/RequestsModal/RequestsModal.jsx
  src/components/Table/index.jsx
  src/views/Requests/index.jsx
Labels: ready

#316 #161975567 Change title of residence page
  src/components/AccommodationPanelHeader/index.jsx
  src/views/Dashboard/index.scss
  src/views/Documents/DocumentTable.js
  src/views/Documents/__tests__/__snapshots__/DocumentTable.test.js.snap
Labels: PEER-REVIEW

#306 #161656449 Fix room selection on request modal
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/Date.test.jsx.snap
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetails.test.js
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetailsItem.test.js
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetailsItem.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/redux/actionCreator/availableRoomsActions.js
  src/redux/middleware/availableRoomsSaga.js
  src/redux/reducers/__tests__/availableRooms.test.js
  src/redux/reducers/availableRooms.js
  src/views/Requests/index.jsx
Labels: ready

#312 #161962033 Fix checkbox and multi-trip cancel icon designs in request modal
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/SubmitArea.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Forms/index.scss
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
  yarn.lock
Labels: ready

#319 #161975169 Fix badge on the approvals modal upon approval
  src/components/Table/index.jsx
  src/views/Approvals/index.jsx
Labels: ready

#318 #161983423 Fix checkin/checkout UI design
  src/components/CheckInTable/CheckInTable.scss
  src/components/CheckInTable/index.jsx
  src/components/RoleDetailsTable/RoleDetailsTable.scss
  src/views/CheckIn/index.jsx
Labels: ready

#311 #161888672 Fix position and styles for save changes and cancel button.…
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/filterDropdownSelect.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Forms/ProfileForm/FormFieldsets/ProfileDetails.jsx
  src/components/Forms/ProfileForm/ProfileForm.scss
  src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
  src/components/Forms/ProfileForm/index.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap
  src/views/UserProfile/UserProfile.scss
  src/views/UserProfile/__tests__/UserProfile.test.js
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
  src/views/UserProfile/index.jsx
Labels: PEER-REVIEW

#331 #162080188 Reposition the notification pane
  src/components/notification-pane/_notificationPane.scss
Labels: ready

#329 #162039447 Fix bug on delete first room of guest house
  src/components/Forms/NewAccommodationForm/FormFieldsets/AccommodationDetails.jsx
  src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
Labels: ready

#326 #161445627 Add depature time to ticket details on checklist submission
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelCheckList/CheckListSubmissionForm.jsx
  src/components/TravelCheckList/SubmissionFormSets.jsx
  src/components/TravelCheckList/__tests__/CheckListSubmissionForm.tests.js
  src/components/TravelCheckList/travelSubmission.scss
  yarn.lock
Labels: ready

#327 #162039621 Fix file download issue on travel-readiness
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/CheckInTable/__tests__/__snapshots__/CheckInTable.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelReadiness/index.jsx
  src/redux/middleware/travelReadinessSaga.js
  src/services/ReadinessAPI.js
  src/services/__tests__/ReadinessAPI.test.js
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
Labels: ready

#328 #162011054 Fix bug with renaming travel document modal
  src/views/Documents/Documents.scss
  src/views/Documents/index.js
Labels: ready

#333 #162006704 Add responsiveness to requests modal
  src/components/Forms/FormsAPI/Input/_input.scss
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/modal/_modal.scss
Labels: ready

#334 # 162007599 Validate file uploads
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewDocumentForm/NewDocumentForm.scss
  src/components/Forms/NewDocumentForm/__tests__/NewDocumentForm.test.js
  src/components/Forms/NewDocumentForm/__tests__/__snapshots__/NewDocumentForm.test.js.snap
  src/components/Forms/NewDocumentForm/index.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/Dashboard/DashboardContext/__tests__/FilterContext.test.js
  src/views/Dashboard/__tests__/Dashboard.test.js
  src/views/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
Labels: ready

#321 #162008362 Fix travel checklist submissions issues
  src/components/Forms/index.js
  src/components/Table/Table.scss
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/TableMenu/TableMenu.jsx
  src/components/TravelCheckList/CheckListSubmissionForm.jsx
  src/components/TravelCheckList/CheckListSubmissions.jsx
  src/components/TravelCheckList/SubmissionFormSets.jsx
  src/components/TravelCheckList/SubmissionItem.jsx
  src/components/TravelCheckList/SubmissionsUtils.jsx
  src/components/TravelCheckList/__tests__/CheckListSubmissionForm.tests.js
  src/components/TravelCheckList/__tests__/CheckListSubmissions.test.js
  src/components/TravelCheckList/__tests__/SubmissionFormSets.tests.js
  src/components/TravelCheckList/__tests__/SubmissionItem.test.js
  src/components/TravelCheckList/__tests__/TravelCheckList.test.js
  src/components/TravelCheckList/index.jsx
  src/components/TravelCheckList/travelChecklistMockData.js
  src/components/TravelCheckList/travelSubmission.scss
  src/customStyles/toast.scss
  src/helper/travelChecklist-helper.js
  src/mockData/checklistSubmissionMockData.js
  src/mockData/travelChecklistMockData.js
  src/redux/__mocks__/travelChecklistsMockData.js
  src/redux/actionCreator/__tests__/checkListSubmissionActions.test.js
  src/redux/actionCreator/__tests__/fileUploadActions.test.js
  src/redux/actionCreator/checkListSubmissionActions.js
  src/redux/actionCreator/fileUploadActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/checklistSubmissionSaga.test.js
  src/redux/middleware/__tests__/fileUploadSaga.test.js
  src/redux/middleware/checklistSubmissionSaga.js
  src/redux/middleware/fileUploadSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/checkListSubmission.test.js
  src/redux/reducers/__tests__/fileUpload.test.js
  src/redux/reducers/__tests__/submission.test.js
  src/redux/reducers/__tests__/travelChecklist.test.js
  src/redux/reducers/checklistSubmission.js
  src/redux/reducers/fileUploads.js
  src/redux/reducers/index.js
  src/services/FileUploadAPI.js
  src/services/__tests__/ChecklistSubmissionAPI.test.js
  src/services/__tests__/FileUploadAPI.test.js
  src/services/__tests__/submissionAPI.test.js
  src/services/__tests__/travelChecklistAPI.test.js
  src/services/checklistSubmissionAPI.js
  src/views/Approvals/__tests__/Approvals.test.js
  src/views/Approvals/index.jsx
  src/views/Checklist/__tests__/index.js
  src/views/Checklist/index.jsx
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/index.jsx
Labels: ready

#338 #161981260 Change multi-trip return date
  src/components/Forms/FormsAPI/index.js
  src/components/Forms/FormsMetadata/NewRequestFormMetadata/inputLabels.js
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/RequestsModal/TripDetails/index.jsx
  src/components/TravelCheckList/travelSubmission.scss
Labels: ready

#341 #162159462 Create content placeholder loaders on dashboard
  package.json
  src/components/AnalyticsReport/__tests__/AnalyticsReport.test.js
  src/components/AnalyticsReport/index.jsx
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/AddRoleForm/__tests__/__snapshots__/AddRoleForm.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewUserRoleForm/__tests__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/Placeholders/AnalyticsCardPlaceholder.jsx
  src/components/Placeholders/ChartCardPlaceholder.jsx
  src/components/Placeholders/TravelCalendarPlaceholder.jsx
  src/components/Placeholders/TravelReadinessPlaceholder.jsx
  src/components/Placeholders/TripsPerMonthPlaceholder.jsx
  src/components/Placeholders/__tests__/AnalyticsCardPlaceholder.test.js
  src/components/Placeholders/__tests__/ChartCardPlaceholder.test.js
  src/components/Placeholders/__tests__/TravelCalendarPlaceholder.test.js
  src/components/Placeholders/__tests__/TravelReadinessPlaceholder.test.js
  src/components/Placeholders/__tests__/TripsPerMonthPlaceholder.test.js
  src/components/Placeholders/__tests__/__snapshots__/AnalyticsCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/ChartCardPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelCalendarPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TravelReadinessPlaceholder.test.js.snap
  src/components/Placeholders/__tests__/__snapshots__/TripsPerMonthPlaceholder.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Spinner/__tests__/Spinner.test.js
  src/components/Spinner/__tests__/__snapshots__/Spinner.test.js.snap
  src/components/Spinner/index.jsx
  src/components/Spinner/index.scss
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/TimelineVerticalAxis/__tests__/__snapshots__/RoomLabel.test.jsx.snap
  src/components/Timeline/TimelineVerticalAxis/_tests_/__snapshots__/RoomLabelFaultStatus.test.js.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelCalendar/TravelCalendar.scss
  src/components/TravelCalendar/__tests__/TravelCalendar.test.js
  src/components/TravelCalendar/index.jsx
  src/components/TravelReadiness/__tests__/travelReadiness.test.js
  src/components/TravelReadiness/index.jsx
  src/views/Analytics/__tests__/Analytics.test.js
  src/views/Analytics/index.jsx
  src/views/Analytics/index.scss
  src/views/Dashboard/__tests__/Dashboard.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  yarn.lock
Labels: ready

#324 #161888236 Accommodation selection field on request initiation form
  src/components/Forms/NewDocumentForm/NewDocumentForm.scss
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetailsItem.test.js
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetailsItem.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/views/Analytics/__tests__/__snapshots__/Analytics.test.js.snap
Labels: PEER-REVIEW

#344 #162046605 Link pending requests card to my verifications page
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/views/Analytics/__tests__/Analytics.test.js
  src/views/Analytics/__tests__/__snapshots__/Analytics.test.js.snap
  src/views/Analytics/index.jsx
Labels: ready

#337 #161051781 User can delete a request with 'open' status
  src/components/Table/Table.scss
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/TableMenu/TableMenu.jsx
  src/components/TableMenu/__tests__/TableMenu.test.jsx
  src/images/deleted.svg
  src/redux/actionCreator/__tests__/requestActions.test.js
  src/redux/actionCreator/requestActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/requestsSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/requestsSaga.js
  src/redux/reducers/__tests__/requests.test.js
  src/redux/reducers/requests.js
  src/services/RequestAPI.js
  src/services/__tests__/RequestAPI.test.js
  src/views/Documents/DeleteModal.jsx
  src/views/Documents/__tests__/DeleteModal.test.js
  src/views/Documents/index.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/index.jsx
Labels: ready

#346 #161374570 Connect to travel calendar API
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelCalendar/TravelCalendar.scss
  src/components/TravelCalendar/index.jsx
  src/components/TravelCalendarDetails/__tests__/TravelCalendarDetails.test.js
  src/components/TravelCalendarDetails/__tests__/__snapshots__/TravelCalendarDetails.test.js.snap
  src/components/TravelCalendarDetails/index.jsx
  src/redux/reducers/travelCalendar.js
  src/services/TravelCalendarAPI.js
  src/services/__tests__/TravelCalendarAPI.test.js
  src/views/Documents/__tests__/__snapshots__/DeleteModal.test.js.snap
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
Labels: ready

#342 #162154742 Fix Upload errors for files with filenames starting with digits
  src/components/Forms/NewDocumentForm/__tests__/NewDocumentForm.test.js
  src/components/Forms/NewDocumentForm/index.jsx
Labels: ready

#343 #161545272 Reformat error message for failed validation
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/middleware/__tests__/commentsSaga.test.js
  src/redux/middleware/__tests__/documentSaga.test.js
  src/redux/middleware/__tests__/requestsSaga.test.js
  src/redux/middleware/__tests__/travelChecklistSaga.test.js
  src/redux/middleware/__tests__/travelReadinessSaga.test.js
  src/redux/middleware/__tests__/tripsAnalyticsSaga.test.js
  src/redux/middleware/__tests__/tripsSaga.test.js
  src/services/__tests__/apiErrorHandler.test.js
  src/services/apiErrorHandler.js
  src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap
Labels: ready

#336 #161925899 Implement view documents for approved requests
  src/components/Preloader/__tests__/Preloader.test.js
  src/components/RequestsModal/Attachments/Attachments.jsx
  src/components/RequestsModal/Attachments/Attachments.scss
  src/components/RequestsModal/Attachments/_tests_/__snapshots__/attachments.test.js.snap
  src/components/RequestsModal/Attachments/_tests_/attachments.test.js
  src/components/RequestsModal/CommentBox/_CommentBox.scss
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/RequestsModal.scss
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/images/icons/attach_file.svg
  src/images/icons/attachmentDownload.svg
  src/redux/actionCreator/__tests__/attachments.test.js
  src/redux/actionCreator/attachmentActions.js
  src/redux/actionCreator/index.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/DocumentSaga.js
  src/redux/middleware/__tests__/attachments.test.js
  src/redux/middleware/attachmentsSaga.js
  src/redux/middleware/index.js
  src/redux/reducers/__tests__/attachments.test.js
  src/redux/reducers/attachments.js
  src/redux/reducers/index.js
  src/views/Attachments/_tests_/__snapshots__/attachments.test.js.snap
  src/views/Attachments/_tests_/attachments.test.js
  src/views/Attachments/index.js
  src/views/Documents/index.js
Labels: ready

#340 #162045684 Enable travel team members verify requests
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/LeftSideBar/Metadata/index.js
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/ConfirmDialog/ConfirmDialog.jsx
  src/components/RequestsModal/ConfirmDialog/ConfirmDialog.scss
  src/components/RequestsModal/RequestModalHelper.js
  src/components/RequestsModal/RequestsModal.jsx
  src/components/RequestsModal/__tests__/RequestsModal.test.js
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Table/Table.scss
  src/components/Table/index.jsx
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/VerificationsPanelHeader/__tests__/ApprovalsPanelHeader.test.js
  src/components/VerificationsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
  src/components/VerificationsPanelHeader/index.jsx
  src/components/button-group/ButtonGroup.jsx
  src/redux/reducers/approvals.js
  src/routes/index.js
  src/services/__tests__/ApprovalAPI.test.js
  src/services/approvalsAPI.js
  src/views/Verifications/__tests__/Verifications.test.js
  src/views/Verifications/index.jsx
Labels: ready

#347 #161699088 Fix reloading issues on the trip planner page.
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewChecklistForm/__tests__/index.js
  src/components/Forms/NewChecklistForm/index.jsx
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/redux/actionCreator/__tests__/travelChecklistActions.test.js
  src/redux/actionCreator/travelChecklistActions.js
  src/redux/constants/actionTypes.js
  src/redux/middleware/__tests__/travelChecklistSaga.test.js
  src/redux/middleware/index.js
  src/redux/middleware/travelChecklistSaga.js
  src/redux/reducers/__tests__/travelChecklist.test.js
  src/redux/reducers/travelChecklist.js
  src/views/Checklist/__tests__/index.js
  src/views/Checklist/index.jsx
Labels: ready

#350 #162192282 Fix checklist submissions issues
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Table/Table.scss
  src/components/Table/index.jsx
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelCheckList/SubmissionsUtils.jsx
  src/hoc/authHoc.js
  src/views/Requests/__tests__/Requests.test.js
  src/views/Requests/index.jsx
Labels: TC/TTL Review

#349 #162181076 Fix spacing of dropdown input
  src/components/Forms/NewAccommodationForm/FormFieldsets/AccommodationDetails.jsx
  src/components/Forms/ProfileForm/ProfileForm.scss
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/TripDetails.scss
Labels: ready

#352 #162192899 Auto-fill multicity request origin field
  src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewRequestForm/NewRequestForm.scss
Labels: ready

#339 #162046982 Toggle travel readiness for outflow and inflow
  src/components/AnalyticsReport/index.jsx
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelReadiness/TravelReadiness.scss
  src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
  src/components/TravelReadiness/__tests__/travelReadiness.test.js
  src/components/TravelReadiness/index.jsx
  src/redux/middleware/travelReadinessSaga.js
  src/services/ReadinessAPI.js
  src/services/__tests__/ReadinessAPI.test.js
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
Labels: ready

#357 #162232273 Allow travel team members to view dashboard
  src/components/AnalyticsReport/__tests__/__snapshots__/AnalyticsReport.test.js.snap
  src/components/LeftSideBar/Metadata/index.js
  src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
  src/components/TravelReadiness/index.jsx
  src/views/Dashboard/index.jsx
Labels: TC/TTL Review

#362 #162237283 Fix notification badge on verification page.
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/ProfileForm/ProfileForm.scss
  src/components/Table/__tests__/Table.test.js
  src/components/Table/index.jsx
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/button-group/ButtonGroup.jsx
Labels: TC/TTL Review

#358 #162239807 Create content loaders on requests page
  src/components/AnalyticsReport/__tests__/__snapshots__/AnalyticsReport.test.js.snap
  src/components/ApprovalsPanelHeader/index.jsx
  src/components/Hoc/withLoading.js
  src/components/Placeholders/RequestsPlaceholder.jsx
  src/components/Placeholders/__tests__/RequestsPlaceholder.test.test.js
  src/components/Placeholders/__tests__/__snapshots__/RequestsPlaceholder.test.test.js.snap
  src/components/RequestPanelHeader/RequestPanelHeader.jsx
  src/components/Table/index.jsx
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/VerificationsPanelHeader/index.jsx
  src/views/Approvals/index.jsx
  src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
  src/views/Requests/index.jsx
  src/views/Verifications/index.jsx
Labels: TC/TTL Review

#365 #162261103 Fix text-area misalignment
  src/components/TravelCheckList/travelSubmission.scss
Labels: TC/TTL Review

#360 #162156678 Fix(validate role field): Role field should display an error when empty
  src/components/Forms/AddRoleForm/__tests__/__snapshots__/AddRoleForm.test.js.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/filterDropdownSelect.test.jsx.snap
  src/components/Forms/FormsAPI/Input/InputFields/__tests__/filterDropdownSelect.test.jsx
  src/components/Forms/FormsAPI/Input/InputFields/filterDropdownSelect.jsx
  src/components/Forms/FormsAPI/Input/_input.scss
  src/components/Forms/FormsAPI/Input/index.jsx
  src/components/Forms/FormsAPI/formEventHandlers/eventHandlerCreators.js
  src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
  src/components/Forms/NewChecklistForm/__tests__/index.js
  src/components/Forms/NewDocumentForm/__tests__/__snapshots__/NewDocumentForm.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/NewRequestForm/NewRequestForm.jsx
  src/components/Forms/NewUserRoleForm/__tests__/__snapshots__/NewUserRoleForm.test.js.snap
  src/components/Forms/ProfileForm/FormFieldsets/ProfileDetails.jsx
  src/components/Forms/ProfileForm/ProfileForm.scss
  src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
  src/components/Forms/ProfileForm/index.jsx
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
  src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
Labels: TC/TTL Review

#348 #161875591 User can see the right components on the request page after fi…
  .codeclimate.yml
  .eslintrc.json
  cypress/fixtures/requests/no-request.json
  cypress/integration/component/Requests/request.spec.js
  cypress/support/commands.js
  package.json
  yarn.lock
Labels: TC/TTL Review

#359 #161875838 User can logout end to end test
  cypress/integration/component/logout.spec.js
  src/hoc/Layout/index.jsx
Labels: TC/TTL Review

#353 #162173129 Add pagination to the travel calendar
  src/components/Pagination/AnalyticsPagination.jsx
  src/components/Pagination/__tests__/AnalyticsPagination.test.js
  src/components/Pagination/__tests__/__snapshots__/AnalyticsPagination.test.js.snap
  src/components/Pagination/_analyticsPagination.scss
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/TravelCalendar/__tests__/TravelCalendar.test.js
  src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
  src/components/TravelCalendar/index.jsx
  src/components/TravelCalendarDetails/index.jsx
  src/services/TravelCalendarAPI.js
  src/services/__tests__/TravelCalendarAPI.test.js
Labels: TC/TTL Review

#369 #162304867 Modify label on Trips card
  src/components/AnalyticsReport/index.jsx
Labels: TC/TTL Review

#370 #162303455 Outflow for travel-readiness should have departure dates instead
  src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
  src/components/CentreGrid/__tests__/__snapshots__/CentreGrid.test.js.snap
  src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
  src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
  src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
  src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
  src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
  src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
  src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
  src/components/TravelReadiness/__tests__/travelReadiness.test.js
  src/components/TravelReadiness/index.jsx
  src/hoc/Layout/__tests__/__snapshots__/Layout.test.jsx.snap
  src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
  src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
Labels: TC/TTL Review

#354 #162168429 Implement pagination on Travel Readiness Card
  src/components/AnalyticsReport/__tests__/AnalyticsReport.test.js
  src/components/AnalyticsReport/index.jsx
  src/components/AnalyticsReport/index.scss
  src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItem/_leftSideNavItem.scss
  src/components/Pagination/AnalyticsPagination.jsx
  src/components/Pagination/__tests__/AnalyticsPagination.test.js
  src/components/Pagination/__tests__/__snapshots__/AnalyticsPagination.test.js.snap
  src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
  src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
  src/components/TravelCalendarDetails/__tests__/__snapshots__/TravelCalendarDetails.test.js.snap
  src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
  src/components/TravelReadiness/__tests__/travelReadiness.test.js
  src/components/TravelReadiness/index.jsx
  src/redux/__mocks__/mocks.js
  src/redux/middleware/__tests__/travelReadinessSaga.test.js
  src/redux/middleware/travelReadinessSaga.js
  src/redux/reducers/__tests__/readiness.test.js
  src/redux/reducers/readiness.js
Labels: TC/TTL Review
